// 100 nejpoužívanějších ŠPANĚLSKÝCH slov pro tátu.
// Editace: přidej/uprav záznam v tomto poli a ulož. Nic víc není potřeba.
// Pole:
//   id          – jednoznačné číslo (neopakuj)
//   es          – španělsky (u podstatných jmen bez členu; člen je v poli "clen")
//   cz          – česky
//   vyslovnost  – fonetická nápověda; uvádíme jen tam, kde by to šlo přečíst špatně (jinak "")
//   veta_es     – krátká použitelná věta španělsky
//   veta_cz     – její český překlad
//   slovni_druh – "sloveso" | "podstatné jméno" | "přídavné jméno" | "funkční slovo"
//   clen        – "el" / "la" u podstatných jmen, jinak ""
window.SLOVA_ES = [
  // ---------- SLOVESA (30) ----------
  { id: 1, es: "ser", cz: "být (trvale)", vyslovnost: "", veta_es: "Yo soy de la República Checa.", veta_cz: "Jsem z České republiky.", slovni_druh: "sloveso", clen: "" },
  { id: 2, es: "estar", cz: "být (stav, poloha)", vyslovnost: "", veta_es: "¿Dónde estás ahora?", veta_cz: "Kde teď jsi?", slovni_druh: "sloveso", clen: "" },
  { id: 3, es: "tener", cz: "mít", vyslovnost: "", veta_es: "Tengo dos hijos.", veta_cz: "Mám dvě děti.", slovni_druh: "sloveso", clen: "" },
  { id: 4, es: "hacer", cz: "dělat", vyslovnost: "asér", veta_es: "¿Qué haces hoy?", veta_cz: "Co dnes děláš?", slovni_druh: "sloveso", clen: "" },
  { id: 5, es: "ir", cz: "jít, jet", vyslovnost: "", veta_es: "Voy a la playa.", veta_cz: "Jdu na pláž.", slovni_druh: "sloveso", clen: "" },
  { id: 6, es: "poder", cz: "moci", vyslovnost: "", veta_es: "¿Puedes ayudarme?", veta_cz: "Můžeš mi pomoct?", slovni_druh: "sloveso", clen: "" },
  { id: 7, es: "querer", cz: "chtít, mít rád", vyslovnost: "kerér", veta_es: "Quiero un café, por favor.", veta_cz: "Chci kávu, prosím.", slovni_druh: "sloveso", clen: "" },
  { id: 8, es: "saber", cz: "vědět, umět", vyslovnost: "", veta_es: "No sé dónde está.", veta_cz: "Nevím, kde to je.", slovni_druh: "sloveso", clen: "" },
  { id: 9, es: "ver", cz: "vidět", vyslovnost: "", veta_es: "Quiero ver el mar.", veta_cz: "Chci vidět moře.", slovni_druh: "sloveso", clen: "" },
  { id: 10, es: "dar", cz: "dát", vyslovnost: "", veta_es: "¿Me das agua?", veta_cz: "Dáš mi vodu?", slovni_druh: "sloveso", clen: "" },
  { id: 11, es: "hablar", cz: "mluvit", vyslovnost: "ablár", veta_es: "No hablo mucho español.", veta_cz: "Nemluvím moc španělsky.", slovni_druh: "sloveso", clen: "" },
  { id: 12, es: "comer", cz: "jíst", vyslovnost: "", veta_es: "Vamos a comer algo.", veta_cz: "Pojďme si něco sníst.", slovni_druh: "sloveso", clen: "" },
  { id: 13, es: "beber", cz: "pít", vyslovnost: "", veta_es: "¿Quieres beber algo?", veta_cz: "Chceš se něčeho napít?", slovni_druh: "sloveso", clen: "" },
  { id: 14, es: "vivir", cz: "žít, bydlet", vyslovnost: "", veta_es: "Vivo en Praga.", veta_cz: "Bydlím v Praze.", slovni_druh: "sloveso", clen: "" },
  { id: 15, es: "venir", cz: "přijít", vyslovnost: "", veta_es: "¿Vienes conmigo?", veta_cz: "Jdeš se mnou?", slovni_druh: "sloveso", clen: "" },
  { id: 16, es: "decir", cz: "říct", vyslovnost: "decír", veta_es: "¿Qué quieres decir?", veta_cz: "Co tím chceš říct?", slovni_druh: "sloveso", clen: "" },
  { id: 17, es: "poner", cz: "položit, dát", vyslovnost: "", veta_es: "Pon la bolsa aquí.", veta_cz: "Polož tašku sem.", slovni_druh: "sloveso", clen: "" },
  { id: 18, es: "salir", cz: "vyjít, odejít", vyslovnost: "", veta_es: "Salgo de casa a las ocho.", veta_cz: "Odcházím z domu v osm.", slovni_druh: "sloveso", clen: "" },
  { id: 19, es: "llegar", cz: "dorazit, přijet", vyslovnost: "jegár", veta_es: "El tren llega tarde.", veta_cz: "Vlak přijíždí pozdě.", slovni_druh: "sloveso", clen: "" },
  { id: 20, es: "pasar", cz: "stát se, projít", vyslovnost: "", veta_es: "¿Qué pasa?", veta_cz: "Co se děje?", slovni_druh: "sloveso", clen: "" },
  { id: 21, es: "deber", cz: "muset, mít povinnost", vyslovnost: "", veta_es: "Debo trabajar mañana.", veta_cz: "Musím zítra pracovat.", slovni_druh: "sloveso", clen: "" },
  { id: 22, es: "necesitar", cz: "potřebovat", vyslovnost: "necesitár", veta_es: "Necesito ayuda.", veta_cz: "Potřebuju pomoc.", slovni_druh: "sloveso", clen: "" },
  { id: 23, es: "gustar", cz: "líbit se, chutnat", vyslovnost: "", veta_es: "Me gusta el café.", veta_cz: "Mám rád kávu.", slovni_druh: "sloveso", clen: "" },
  { id: 24, es: "comprar", cz: "koupit", vyslovnost: "", veta_es: "Quiero comprar pan.", veta_cz: "Chci koupit chleba.", slovni_druh: "sloveso", clen: "" },
  { id: 25, es: "trabajar", cz: "pracovat", vyslovnost: "trabachár", veta_es: "Trabajo en una tienda.", veta_cz: "Pracuju v obchodě.", slovni_druh: "sloveso", clen: "" },
  { id: 26, es: "entender", cz: "rozumět", vyslovnost: "", veta_es: "No entiendo bien.", veta_cz: "Moc nerozumím.", slovni_druh: "sloveso", clen: "" },
  { id: 27, es: "ayudar", cz: "pomáhat", vyslovnost: "ajudár", veta_es: "¿Puede ayudarme, por favor?", veta_cz: "Můžete mi prosím pomoct?", slovni_druh: "sloveso", clen: "" },
  { id: 28, es: "buscar", cz: "hledat", vyslovnost: "", veta_es: "Busco un hotel.", veta_cz: "Hledám hotel.", slovni_druh: "sloveso", clen: "" },
  { id: 29, es: "encontrar", cz: "najít", vyslovnost: "", veta_es: "No encuentro la llave.", veta_cz: "Nemůžu najít klíč.", slovni_druh: "sloveso", clen: "" },
  { id: 30, es: "pensar", cz: "myslet", vyslovnost: "", veta_es: "Pienso que sí.", veta_cz: "Myslím, že ano.", slovni_druh: "sloveso", clen: "" },

  // ---------- PODSTATNÁ JMÉNA (40) ----------
  { id: 31, es: "día", cz: "den", vyslovnost: "", veta_es: "Buenos días, señor.", veta_cz: "Dobrý den, pane.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 32, es: "casa", cz: "dům, domov", vyslovnost: "", veta_es: "Estoy en casa.", veta_cz: "Jsem doma.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 33, es: "agua", cz: "voda", vyslovnost: "", veta_es: "Quiero un vaso de agua.", veta_cz: "Chci sklenici vody.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 34, es: "tiempo", cz: "čas, počasí", vyslovnost: "", veta_es: "No tengo tiempo.", veta_cz: "Nemám čas.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 35, es: "año", cz: "rok", vyslovnost: "aňo", veta_es: "Tengo sesenta años.", veta_cz: "Je mi šedesát let.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 36, es: "hombre", cz: "muž, člověk", vyslovnost: "ombre", veta_es: "Ese hombre es mi amigo.", veta_cz: "Ten muž je můj přítel.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 37, es: "mujer", cz: "žena", vyslovnost: "mucher", veta_es: "La mujer trabaja aquí.", veta_cz: "Ta žena tady pracuje.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 38, es: "niño", cz: "dítě, kluk", vyslovnost: "niňo", veta_es: "El niño juega en la calle.", veta_cz: "Dítě si hraje na ulici.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 39, es: "amigo", cz: "přítel, kamarád", vyslovnost: "", veta_es: "Es un buen amigo.", veta_cz: "Je to dobrý kamarád.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 40, es: "comida", cz: "jídlo", vyslovnost: "", veta_es: "La comida está muy buena.", veta_cz: "Jídlo je moc dobré.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 41, es: "noche", cz: "noc", vyslovnost: "noče", veta_es: "Buenas noches.", veta_cz: "Dobrou noc.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 42, es: "mañana", cz: "ráno, zítra", vyslovnost: "maňana", veta_es: "Hasta mañana.", veta_cz: "Zítra na shledanou.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 43, es: "gente", cz: "lidé", vyslovnost: "chente", veta_es: "Hay mucha gente aquí.", veta_cz: "Je tu hodně lidí.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 44, es: "cosa", cz: "věc", vyslovnost: "", veta_es: "Es una cosa importante.", veta_cz: "Je to důležitá věc.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 45, es: "vida", cz: "život", vyslovnost: "", veta_es: "Así es la vida.", veta_cz: "Takový je život.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 46, es: "trabajo", cz: "práce", vyslovnost: "trabacho", veta_es: "Me gusta mi trabajo.", veta_cz: "Mám rád svou práci.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 47, es: "ciudad", cz: "město", vyslovnost: "siudad", veta_es: "Madrid es una ciudad grande.", veta_cz: "Madrid je velké město.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 48, es: "país", cz: "země, stát", vyslovnost: "pa-ís", veta_es: "España es un país bonito.", veta_cz: "Španělsko je krásná země.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 49, es: "mundo", cz: "svět", vyslovnost: "", veta_es: "Quiero ver el mundo.", veta_cz: "Chci vidět svět.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 50, es: "coche", cz: "auto", vyslovnost: "koče", veta_es: "El coche es nuevo.", veta_cz: "To auto je nové.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 51, es: "calle", cz: "ulice", vyslovnost: "kaje", veta_es: "Vivo en esta calle.", veta_cz: "Bydlím v této ulici.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 52, es: "dinero", cz: "peníze", vyslovnost: "", veta_es: "No tengo dinero.", veta_cz: "Nemám peníze.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 53, es: "hora", cz: "hodina", vyslovnost: "ora", veta_es: "¿Qué hora es?", veta_cz: "Kolik je hodin?", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 54, es: "semana", cz: "týden", vyslovnost: "", veta_es: "Nos vemos la próxima semana.", veta_cz: "Uvidíme se příští týden.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 55, es: "mes", cz: "měsíc", vyslovnost: "", veta_es: "Voy a España este mes.", veta_cz: "Tento měsíc jedu do Španělska.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 56, es: "nombre", cz: "jméno", vyslovnost: "", veta_es: "¿Cuál es tu nombre?", veta_cz: "Jak se jmenuješ?", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 57, es: "familia", cz: "rodina", vyslovnost: "", veta_es: "Mi familia vive aquí.", veta_cz: "Moje rodina žije tady.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 58, es: "padre", cz: "otec, táta", vyslovnost: "", veta_es: "Mi padre es alto.", veta_cz: "Můj táta je vysoký.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 59, es: "madre", cz: "matka, máma", vyslovnost: "", veta_es: "Mi madre cocina bien.", veta_cz: "Moje máma dobře vaří.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 60, es: "hijo", cz: "syn", vyslovnost: "icho", veta_es: "Su hijo tiene diez años.", veta_cz: "Jeho syn má deset let.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 61, es: "mano", cz: "ruka", vyslovnost: "", veta_es: "Dame la mano.", veta_cz: "Podej mi ruku.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 62, es: "puerta", cz: "dveře", vyslovnost: "puerta", veta_es: "Cierra la puerta, por favor.", veta_cz: "Zavři dveře, prosím.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 63, es: "mesa", cz: "stůl", vyslovnost: "", veta_es: "Una mesa para dos, por favor.", veta_cz: "Stůl pro dva, prosím.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 64, es: "pan", cz: "chleba", vyslovnost: "", veta_es: "Quiero pan con tomate.", veta_cz: "Chci chleba s rajčaty.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 65, es: "café", cz: "káva", vyslovnost: "", veta_es: "Un café con leche, por favor.", veta_cz: "Kávu s mlékem, prosím.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 66, es: "leche", cz: "mléko", vyslovnost: "leče", veta_es: "No tomo leche.", veta_cz: "Nepiju mléko.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 67, es: "baño", cz: "koupelna, záchod", vyslovnost: "baňo", veta_es: "¿Dónde está el baño?", veta_cz: "Kde je záchod?", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 68, es: "playa", cz: "pláž", vyslovnost: "plaja", veta_es: "La playa está cerca.", veta_cz: "Pláž je blízko.", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 69, es: "sol", cz: "slunce", vyslovnost: "", veta_es: "Hoy hace sol.", veta_cz: "Dnes svítí slunce.", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 70, es: "tienda", cz: "obchod", vyslovnost: "", veta_es: "La tienda está cerrada.", veta_cz: "Obchod je zavřený.", slovni_druh: "podstatné jméno", clen: "la" },

  // ---------- PŘÍDAVNÁ JMÉNA (15) ----------
  { id: 71, es: "bueno", cz: "dobrý", vyslovnost: "bueno", veta_es: "Es un vino muy bueno.", veta_cz: "To je moc dobré víno.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 72, es: "malo", cz: "špatný", vyslovnost: "", veta_es: "Hoy hace mal tiempo.", veta_cz: "Dnes je špatné počasí.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 73, es: "grande", cz: "velký", vyslovnost: "grande", veta_es: "Es una casa grande.", veta_cz: "Je to velký dům.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 74, es: "pequeño", cz: "malý", vyslovnost: "pekeňo", veta_es: "Quiero un café pequeño.", veta_cz: "Chci malou kávu.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 75, es: "nuevo", cz: "nový", vyslovnost: "nuevo", veta_es: "Tengo un coche nuevo.", veta_cz: "Mám nové auto.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 76, es: "viejo", cz: "starý", vyslovnost: "viecho", veta_es: "Es un pueblo muy viejo.", veta_cz: "Je to hodně staré městečko.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 77, es: "mucho", cz: "hodně, mnoho", vyslovnost: "mučo", veta_es: "Muchas gracias.", veta_cz: "Mnohokrát děkuji.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 78, es: "poco", cz: "málo", vyslovnost: "", veta_es: "Hablo un poco de español.", veta_cz: "Mluvím trochu španělsky.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 79, es: "bonito", cz: "hezký, pěkný", vyslovnost: "", veta_es: "¡Qué bonito!", veta_cz: "To je hezké!", slovni_druh: "přídavné jméno", clen: "" },
  { id: 80, es: "feo", cz: "ošklivý", vyslovnost: "", veta_es: "El tiempo está feo hoy.", veta_cz: "Počasí je dnes ošklivé.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 81, es: "fácil", cz: "snadný", vyslovnost: "fásil", veta_es: "El español es fácil.", veta_cz: "Španělština je snadná.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 82, es: "difícil", cz: "těžký, obtížný", vyslovnost: "difísil", veta_es: "Es difícil para mí.", veta_cz: "Je to pro mě těžké.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 83, es: "caro", cz: "drahý", vyslovnost: "", veta_es: "Este hotel es muy caro.", veta_cz: "Tento hotel je moc drahý.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 84, es: "barato", cz: "levný", vyslovnost: "", veta_es: "El menú es barato.", veta_cz: "To menu je levné.", slovni_druh: "přídavné jméno", clen: "" },
  { id: 85, es: "feliz", cz: "šťastný", vyslovnost: "felís", veta_es: "Estoy muy feliz hoy.", veta_cz: "Dnes jsem moc šťastný.", slovni_druh: "přídavné jméno", clen: "" },

  // ---------- FUNKČNÍ SLOVA A FRÁZE (15) ----------
  { id: 86, es: "dónde", cz: "kde", vyslovnost: "donde", veta_es: "¿Dónde está la estación?", veta_cz: "Kde je nádraží?", slovni_druh: "funkční slovo", clen: "" },
  { id: 87, es: "cuándo", cz: "kdy", vyslovnost: "kuando", veta_es: "¿Cuándo llega el autobús?", veta_cz: "Kdy přijede autobus?", slovni_druh: "funkční slovo", clen: "" },
  { id: 88, es: "cómo", cz: "jak", vyslovnost: "komo", veta_es: "¿Cómo estás?", veta_cz: "Jak se máš?", slovni_druh: "funkční slovo", clen: "" },
  { id: 89, es: "qué", cz: "co, jaký", vyslovnost: "ke", veta_es: "¿Qué es esto?", veta_cz: "Co je to?", slovni_druh: "funkční slovo", clen: "" },
  { id: 90, es: "por qué", cz: "proč", vyslovnost: "por ke", veta_es: "¿Por qué no vienes?", veta_cz: "Proč nejdeš?", slovni_druh: "funkční slovo", clen: "" },
  { id: 91, es: "porque", cz: "protože", vyslovnost: "porke", veta_es: "No voy porque estoy cansado.", veta_cz: "Nejdu, protože jsem unavený.", slovni_druh: "funkční slovo", clen: "" },
  { id: 92, es: "también", cz: "také", vyslovnost: "tambien", veta_es: "Yo también quiero ir.", veta_cz: "Já chci jet taky.", slovni_druh: "funkční slovo", clen: "" },
  { id: 93, es: "pero", cz: "ale", vyslovnost: "", veta_es: "Quiero ir, pero no puedo.", veta_cz: "Chci jít, ale nemůžu.", slovni_druh: "funkční slovo", clen: "" },
  { id: 94, es: "muy", cz: "velmi, moc", vyslovnost: "muj", veta_es: "Es muy tarde.", veta_cz: "Je moc pozdě.", slovni_druh: "funkční slovo", clen: "" },
  { id: 95, es: "ahora", cz: "teď", vyslovnost: "aora", veta_es: "Tengo que irme ahora.", veta_cz: "Musím teď jít.", slovni_druh: "funkční slovo", clen: "" },
  { id: 96, es: "aquí", cz: "tady", vyslovnost: "akí", veta_es: "Espera aquí, por favor.", veta_cz: "Počkej tady, prosím.", slovni_druh: "funkční slovo", clen: "" },
  { id: 97, es: "allí", cz: "tam", vyslovnost: "ají", veta_es: "El hotel está allí.", veta_cz: "Hotel je tamhle.", slovni_druh: "funkční slovo", clen: "" },
  { id: 98, es: "siempre", cz: "vždy", vyslovnost: "siempre", veta_es: "Siempre tomo café.", veta_cz: "Vždycky si dám kávu.", slovni_druh: "funkční slovo", clen: "" },
  { id: 99, es: "nunca", cz: "nikdy", vyslovnost: "nunka", veta_es: "Nunca voy a la playa.", veta_cz: "Nikdy nechodím na pláž.", slovni_druh: "funkční slovo", clen: "" },
  { id: 100, es: "gracias", cz: "děkuji", vyslovnost: "grasias", veta_es: "Gracias por todo.", veta_cz: "Děkuji za všechno.", slovni_druh: "funkční slovo", clen: "" }
];
