// 500 nejpoužívanějších ANGLICKÝCH slov pro tátu.
// Tento soubor slouží dvěma kurzům: (1) čeština → angličtina (učí se táta) a
// (2) angličtina → čeština (kurz pro anglicky mluvící). U kurzu češtiny se čte
// druhá strana (cz / veta_cz); výslovnost češtiny se dopočítá z pravopisu v index.html.
// Editace: přidej/uprav záznam v tomto poli a ulož. Nic víc není potřeba.
// Pole:
//   id          – jednoznačné číslo (neopakuj). Pořadí = pořadí učení, od nejčastějších.
//   en          – anglicky
//   cz          – česky
//   vyslovnost  – český fonetický přepis (viz legenda níže)
//   veta_en     – krátká použitelná věta anglicky (vždy v přítomném čase)
//   veta_cz     – její český překlad
//   slovni_druh – "sloveso" | "podstatné jméno" | "přídavné jméno"
//                 | "příslovce" | "zájmeno" | "tázací slovo" | "fráze"
//
// CO V SEZNAMU ZÁMĚRNĚ NENÍ:
//   Předložky (of, in, on, with...), spojky (and, but, because...) a členy (the, a, an).
//   Samostatná kartička "of = z, od" se nedá naučit a k ničemu není.
//   Táta je uvidí v příkladových větách, kde dávají smysl.
//
// LEGENDA K VÝSLOVNOSTI (zjednodušeně, aby to šlo přečíst česky):
//   "d" a "s" na místě anglického "th" = jazyk mezi zuby (this = "dys", think = "sink")
//   "w" = zaokrouhlené rty, něco mezi "v" a "u" (water = "wótr")
//   "r" = anglické r se nekmitá, jazyk se nedotýká patra
//   "é" = dlouhá otevřená hláska jako v "bird" ("bérd")
//   "e" v přepisu často odpovídá anglickému krátkému "a" (cat = "ket")
//   Přízvučnou slabiku čti trochu důrazněji – v přepisu ji nevyznačujeme.
window.SLOVA_EN = [
  // ---------- ÚROVEŇ 1: 1–100 (úplný základ) ----------
  { id: 1, en: "be", cz: "být", vyslovnost: "bí", veta_en: "I want to be here.", veta_cz: "Chci tu být.", slovni_druh: "sloveso" },
  { id: 2, en: "have", cz: "mít", vyslovnost: "hev", veta_en: "I have two children.", veta_cz: "Mám dvě děti.", slovni_druh: "sloveso" },
  { id: 3, en: "I", cz: "já", vyslovnost: "aj", veta_en: "I am from Prague.", veta_cz: "Jsem z Prahy.", slovni_druh: "zájmeno" },
  { id: 4, en: "not", cz: "ne (zápor)", vyslovnost: "not", veta_en: "I am not tired.", veta_cz: "Nejsem unavený.", slovni_druh: "zájmeno" },
  { id: 5, en: "he", cz: "on", vyslovnost: "hí", veta_en: "He works here.", veta_cz: "On tady pracuje.", slovni_druh: "zájmeno" },
  { id: 6, en: "you", cz: "ty, vy", vyslovnost: "jů", veta_en: "Are you ready?", veta_cz: "Jsi připravený?", slovni_druh: "zájmeno" },
  { id: 7, en: "do", cz: "dělat", vyslovnost: "dů", veta_en: "What do you do?", veta_cz: "Co děláš?", slovni_druh: "sloveso" },
  { id: 8, en: "his", cz: "jeho", vyslovnost: "hyz", veta_en: "This is his car.", veta_cz: "To je jeho auto.", slovni_druh: "zájmeno" },
  { id: 9, en: "they", cz: "oni", vyslovnost: "dej", veta_en: "They live in Brno.", veta_cz: "Bydlí v Brně.", slovni_druh: "zájmeno" },
  { id: 10, en: "we", cz: "my", vyslovnost: "wí", veta_en: "We are here.", veta_cz: "Jsme tady.", slovni_druh: "zájmeno" },
  { id: 11, en: "say", cz: "říct", vyslovnost: "sej", veta_en: "I want to say thank you.", veta_cz: "Chci říct děkuji.", slovni_druh: "sloveso" },
  { id: 12, en: "her", cz: "její; ji", vyslovnost: "hér", veta_en: "This is her house.", veta_cz: "To je její dům.", slovni_druh: "zájmeno" },
  { id: 13, en: "she", cz: "ona", vyslovnost: "ší", veta_en: "She is my wife.", veta_cz: "To je moje žena.", slovni_druh: "zájmeno" },
  { id: 14, en: "will", cz: "budu (budoucí čas)", vyslovnost: "wyl", veta_en: "I will call you.", veta_cz: "Zavolám ti.", slovni_druh: "sloveso" },
  { id: 15, en: "my", cz: "můj", vyslovnost: "maj", veta_en: "This is my son.", veta_cz: "To je můj syn.", slovni_druh: "zájmeno" },
  { id: 16, en: "would", cz: "by (podmiňovací způsob)", vyslovnost: "wud", veta_en: "I would like a coffee.", veta_cz: "Dal bych si kávu.", slovni_druh: "sloveso" },
  { id: 17, en: "what", cz: "co", vyslovnost: "wot", veta_en: "What is this?", veta_cz: "Co to je?", slovni_druh: "tázací slovo" },
  { id: 18, en: "who", cz: "kdo", vyslovnost: "hú", veta_en: "Who is that man?", veta_cz: "Kdo je ten muž?", slovni_druh: "tázací slovo" },
  { id: 19, en: "get", cz: "dostat, sehnat", vyslovnost: "get", veta_en: "Where can I get a ticket?", veta_cz: "Kde seženu lístek?", slovni_druh: "sloveso" },
  { id: 20, en: "which", cz: "který", vyslovnost: "wyč", veta_en: "Which one do you want?", veta_cz: "Který chcete?", slovni_druh: "tázací slovo" },
  { id: 21, en: "go", cz: "jít, jet", vyslovnost: "gou", veta_en: "I go home now.", veta_cz: "Teď jdu domů.", slovni_druh: "sloveso" },
  { id: 22, en: "me", cz: "mě, mně", vyslovnost: "mí", veta_en: "Give it to me, please.", veta_cz: "Dej mi to, prosím.", slovni_druh: "zájmeno" },
  { id: 23, en: "when", cz: "kdy, když", vyslovnost: "wen", veta_en: "When does it start?", veta_cz: "Kdy to začíná?", slovni_druh: "tázací slovo" },
  { id: 24, en: "make", cz: "udělat, vyrobit", vyslovnost: "mejk", veta_en: "I make coffee every morning.", veta_cz: "Každé ráno dělám kávu.", slovni_druh: "sloveso" },
  { id: 25, en: "can", cz: "moci, umět", vyslovnost: "ken", veta_en: "Can you help me?", veta_cz: "Můžete mi pomoct?", slovni_druh: "sloveso" },
  { id: 26, en: "like", cz: "mít rád; jako", vyslovnost: "lajk", veta_en: "I like this music.", veta_cz: "Líbí se mi tahle hudba.", slovni_druh: "sloveso" },
  { id: 27, en: "time", cz: "čas", vyslovnost: "tajm", veta_en: "I have no time.", veta_cz: "Nemám čas.", slovni_druh: "podstatné jméno" },
  { id: 28, en: "no", cz: "ne, žádný", vyslovnost: "nou", veta_en: "No, thank you.", veta_cz: "Ne, děkuji.", slovni_druh: "zájmeno" },
  { id: 29, en: "just", cz: "právě, jenom", vyslovnost: "džast", veta_en: "I just want a coffee.", veta_cz: "Chci jen kávu.", slovni_druh: "příslovce" },
  { id: 30, en: "him", cz: "ho, jemu", vyslovnost: "hym", veta_en: "I know him.", veta_cz: "Znám ho.", slovni_druh: "zájmeno" },
  { id: 31, en: "know", cz: "vědět, znát", vyslovnost: "nou", veta_en: "I do not know.", veta_cz: "Nevím.", slovni_druh: "sloveso" },
  { id: 32, en: "take", cz: "vzít", vyslovnost: "tejk", veta_en: "Take an umbrella.", veta_cz: "Vezmi si deštník.", slovni_druh: "sloveso" },
  { id: 33, en: "people", cz: "lidé", vyslovnost: "pípl", veta_en: "There are many people here.", veta_cz: "Je tu hodně lidí.", slovni_druh: "podstatné jméno" },
  { id: 34, en: "year", cz: "rok", vyslovnost: "jír", veta_en: "I am sixty years old.", veta_cz: "Je mi šedesát let.", slovni_druh: "podstatné jméno" },
  { id: 35, en: "your", cz: "tvůj, váš", vyslovnost: "jór", veta_en: "Is this your seat?", veta_cz: "Je to vaše místo?", slovni_druh: "zájmeno" },
  { id: 36, en: "good", cz: "dobrý", vyslovnost: "gud", veta_en: "The food is very good.", veta_cz: "Jídlo je moc dobré.", slovni_druh: "přídavné jméno" },
  { id: 37, en: "some", cz: "nějaký, trochu", vyslovnost: "sam", veta_en: "I need some water.", veta_cz: "Potřebuju trochu vody.", slovni_druh: "zájmeno" },
  { id: 38, en: "could", cz: "mohl by", vyslovnost: "kud", veta_en: "Could you help me?", veta_cz: "Mohl byste mi pomoct?", slovni_druh: "sloveso" },
  { id: 39, en: "them", cz: "je, jim", vyslovnost: "dem", veta_en: "I see them.", veta_cz: "Vidím je.", slovni_druh: "zájmeno" },
  { id: 40, en: "see", cz: "vidět", vyslovnost: "sí", veta_en: "I want to see the sea.", veta_cz: "Chci vidět moře.", slovni_druh: "sloveso" },
  { id: 41, en: "other", cz: "jiný, druhý", vyslovnost: "adr", veta_en: "The other room is free.", veta_cz: "Ten druhý pokoj je volný.", slovni_druh: "přídavné jméno" },
  { id: 42, en: "then", cz: "potom, tehdy", vyslovnost: "den", veta_en: "See you then.", veta_cz: "Tak potom na shledanou.", slovni_druh: "příslovce" },
  { id: 43, en: "now", cz: "teď", vyslovnost: "nau", veta_en: "I am busy now.", veta_cz: "Teď mám práci.", slovni_druh: "příslovce" },
  { id: 44, en: "look", cz: "dívat se, vypadat", vyslovnost: "luk", veta_en: "Look at this.", veta_cz: "Podívej se na tohle.", slovni_druh: "sloveso" },
  { id: 45, en: "come", cz: "přijít", vyslovnost: "kam", veta_en: "Come here, please.", veta_cz: "Pojďte sem, prosím.", slovni_druh: "sloveso" },
  { id: 46, en: "think", cz: "myslet", vyslovnost: "sink", veta_en: "I think so.", veta_cz: "Myslím, že ano.", slovni_druh: "sloveso" },
  { id: 47, en: "also", cz: "také", vyslovnost: "ólsou", veta_en: "I also speak German.", veta_cz: "Mluvím taky německy.", slovni_druh: "příslovce" },
  { id: 48, en: "back", cz: "zpátky; záda", vyslovnost: "bek", veta_en: "I am back home.", veta_cz: "Jsem zpátky doma.", slovni_druh: "příslovce" },
  { id: 49, en: "use", cz: "použít", vyslovnost: "júz", veta_en: "Can I use your phone?", veta_cz: "Můžu použít váš telefon?", slovni_druh: "sloveso" },
  { id: 50, en: "how", cz: "jak", vyslovnost: "hau", veta_en: "How are you?", veta_cz: "Jak se máte?", slovni_druh: "tázací slovo" },
  { id: 51, en: "work", cz: "práce; pracovat", vyslovnost: "wérk", veta_en: "I work in a shop.", veta_cz: "Pracuju v obchodě.", slovni_druh: "sloveso" },
  { id: 52, en: "first", cz: "první", vyslovnost: "férst", veta_en: "The first day is hard.", veta_cz: "První den je těžký.", slovni_druh: "přídavné jméno" },
  { id: 53, en: "well", cz: "dobře", vyslovnost: "wel", veta_en: "He speaks English well.", veta_cz: "Mluví dobře anglicky.", slovni_druh: "příslovce" },
  { id: 54, en: "way", cz: "cesta, způsob", vyslovnost: "wej", veta_en: "Which way to the station?", veta_cz: "Kudy na nádraží?", slovni_druh: "podstatné jméno" },
  { id: 55, en: "even", cz: "dokonce, i", vyslovnost: "ívn", veta_en: "Even my wife likes it.", veta_cz: "Dokonce i mojí ženě se to líbí.", slovni_druh: "příslovce" },
  { id: 56, en: "new", cz: "nový", vyslovnost: "ňjú", veta_en: "I have a new phone.", veta_cz: "Mám nový telefon.", slovni_druh: "přídavné jméno" },
  { id: 57, en: "want", cz: "chtít", vyslovnost: "wont", veta_en: "I want to go home.", veta_cz: "Chci jít domů.", slovni_druh: "sloveso" },
  { id: 58, en: "any", cz: "nějaký, žádný", vyslovnost: "eny", veta_en: "Do you have any questions?", veta_cz: "Máte nějaké otázky?", slovni_druh: "zájmeno" },
  { id: 59, en: "give", cz: "dát", vyslovnost: "gyv", veta_en: "Give me a minute.", veta_cz: "Dej mi minutu.", slovni_druh: "sloveso" },
  { id: 60, en: "day", cz: "den", vyslovnost: "dej", veta_en: "Have a nice day.", veta_cz: "Hezký den.", slovni_druh: "podstatné jméno" },
  { id: 61, en: "us", cz: "nás, nám", vyslovnost: "as", veta_en: "Come with us.", veta_cz: "Pojď s námi.", slovni_druh: "zájmeno" },
  { id: 62, en: "very", cz: "velmi, moc", vyslovnost: "very", veta_en: "The coffee is very hot.", veta_cz: "Káva je moc horká.", slovni_druh: "příslovce" },
  { id: 63, en: "much", cz: "hodně (nepočitatelné)", vyslovnost: "mač", veta_en: "How much is it?", veta_cz: "Kolik to stojí?", slovni_druh: "zájmeno" },
  { id: 64, en: "many", cz: "hodně (počitatelné)", vyslovnost: "meny", veta_en: "Many people speak English.", veta_cz: "Hodně lidí mluví anglicky.", slovni_druh: "zájmeno" },
  { id: 65, en: "here", cz: "tady", vyslovnost: "hír", veta_en: "I live here.", veta_cz: "Bydlím tady.", slovni_druh: "příslovce" },
  { id: 66, en: "where", cz: "kde, kam", vyslovnost: "wér", veta_en: "Where is the toilet?", veta_cz: "Kde je záchod?", slovni_druh: "tázací slovo" },
  { id: 67, en: "why", cz: "proč", vyslovnost: "waj", veta_en: "Why not?", veta_cz: "Proč ne?", slovni_druh: "tázací slovo" },
  { id: 68, en: "thing", cz: "věc", vyslovnost: "sing", veta_en: "One more thing.", veta_cz: "Ještě jedna věc.", slovni_druh: "podstatné jméno" },
  { id: 69, en: "man", cz: "muž", vyslovnost: "men", veta_en: "That man is my neighbour.", veta_cz: "Ten muž je můj soused.", slovni_druh: "podstatné jméno" },
  { id: 70, en: "woman", cz: "žena", vyslovnost: "wumen", veta_en: "The woman at the desk is kind.", veta_cz: "Ta žena na recepci je milá.", slovni_druh: "podstatné jméno" },
  { id: 71, en: "child", cz: "dítě", vyslovnost: "čajld", veta_en: "The child is sleeping.", veta_cz: "Dítě spí.", slovni_druh: "podstatné jméno" },
  { id: 72, en: "water", cz: "voda", vyslovnost: "wótr", veta_en: "A glass of water, please.", veta_cz: "Sklenici vody, prosím.", slovni_druh: "podstatné jméno" },
  { id: 73, en: "food", cz: "jídlo", vyslovnost: "fúd", veta_en: "The food here is great.", veta_cz: "Jídlo je tu skvělé.", slovni_druh: "podstatné jméno" },
  { id: 74, en: "house", cz: "dům", vyslovnost: "haus", veta_en: "They have a small house.", veta_cz: "Mají malý dům.", slovni_druh: "podstatné jméno" },
  { id: 75, en: "home", cz: "domov, doma", vyslovnost: "houm", veta_en: "I am going home.", veta_cz: "Jdu domů.", slovni_druh: "podstatné jméno" },
  { id: 76, en: "car", cz: "auto", vyslovnost: "kár", veta_en: "My car is old.", veta_cz: "Moje auto je staré.", slovni_druh: "podstatné jméno" },
  { id: 77, en: "money", cz: "peníze", vyslovnost: "many", veta_en: "I have no money with me.", veta_cz: "Nemám u sebe peníze.", slovni_druh: "podstatné jméno" },
  { id: 78, en: "name", cz: "jméno", vyslovnost: "nejm", veta_en: "What is your name?", veta_cz: "Jak se jmenujete?", slovni_druh: "podstatné jméno" },
  { id: 79, en: "place", cz: "místo", vyslovnost: "plejs", veta_en: "This is a nice place.", veta_cz: "Tohle je pěkné místo.", slovni_druh: "podstatné jméno" },
  { id: 80, en: "room", cz: "pokoj, místnost", vyslovnost: "rúm", veta_en: "I have a room for two nights.", veta_cz: "Mám pokoj na dvě noci.", slovni_druh: "podstatné jméno" },
  { id: 81, en: "city", cz: "město", vyslovnost: "syty", veta_en: "Prague is a beautiful city.", veta_cz: "Praha je krásné město.", slovni_druh: "podstatné jméno" },
  { id: 82, en: "country", cz: "země, stát", vyslovnost: "kantry", veta_en: "Which country are you from?", veta_cz: "Z jaké jste země?", slovni_druh: "podstatné jméno" },
  { id: 83, en: "week", cz: "týden", vyslovnost: "wík", veta_en: "See you next week.", veta_cz: "Uvidíme se příští týden.", slovni_druh: "podstatné jméno" },
  { id: 84, en: "month", cz: "měsíc (období)", vyslovnost: "mans", veta_en: "I am here for a month.", veta_cz: "Jsem tady na měsíc.", slovni_druh: "podstatné jméno" },
  { id: 85, en: "hour", cz: "hodina", vyslovnost: "aur", veta_en: "We wait one hour.", veta_cz: "Čekáme hodinu.", slovni_druh: "podstatné jméno" },
  { id: 86, en: "minute", cz: "minuta", vyslovnost: "mynyt", veta_en: "Just a minute, please.", veta_cz: "Moment, prosím.", slovni_druh: "podstatné jméno" },
  { id: 87, en: "morning", cz: "ráno, dopoledne", vyslovnost: "mórnyng", veta_en: "Good morning!", veta_cz: "Dobré ráno!", slovni_druh: "podstatné jméno" },
  { id: 88, en: "night", cz: "noc", vyslovnost: "najt", veta_en: "Good night.", veta_cz: "Dobrou noc.", slovni_druh: "podstatné jméno" },
  { id: 89, en: "today", cz: "dnes", vyslovnost: "tudej", veta_en: "What are we doing today?", veta_cz: "Co dnes děláme?", slovni_druh: "příslovce" },
  { id: 90, en: "tomorrow", cz: "zítra", vyslovnost: "temorou", veta_en: "See you tomorrow.", veta_cz: "Uvidíme se zítra.", slovni_druh: "příslovce" },
  { id: 91, en: "yesterday", cz: "včera", vyslovnost: "jestrdej", veta_en: "Yesterday, today, tomorrow.", veta_cz: "Včera, dnes, zítra.", slovni_druh: "příslovce" },
  { id: 92, en: "always", cz: "vždycky", vyslovnost: "ólwejz", veta_en: "He is always late.", veta_cz: "Vždycky chodí pozdě.", slovni_druh: "příslovce" },
  { id: 93, en: "never", cz: "nikdy", vyslovnost: "nevr", veta_en: "I never drink coffee at night.", veta_cz: "Večer nikdy nepiju kávu.", slovni_druh: "příslovce" },
  { id: 94, en: "sometimes", cz: "někdy, občas", vyslovnost: "samtajmz", veta_en: "Sometimes I walk to work.", veta_cz: "Občas chodím do práce pěšky.", slovni_druh: "příslovce" },
  { id: 95, en: "often", cz: "často", vyslovnost: "ofn", veta_en: "We often go there.", veta_cz: "Chodíme tam často.", slovni_druh: "příslovce" },
  { id: 96, en: "again", cz: "znovu, zase", vyslovnost: "egen", veta_en: "Say it again, please.", veta_cz: "Řekněte to prosím znovu.", slovni_druh: "příslovce" },
  { id: 97, en: "still", cz: "pořád, stále", vyslovnost: "styl", veta_en: "He is still at work.", veta_cz: "Pořád je v práci.", slovni_druh: "příslovce" },
  { id: 98, en: "already", cz: "už", vyslovnost: "ólredy", veta_en: "I am already here.", veta_cz: "Už jsem tady.", slovni_druh: "příslovce" },
  { id: 99, en: "soon", cz: "brzy", vyslovnost: "sún", veta_en: "I will be there soon.", veta_cz: "Brzy tam budu.", slovni_druh: "příslovce" },
  { id: 100, en: "late", cz: "pozdě, pozdní", vyslovnost: "lejt", veta_en: "Sorry, I am late.", veta_cz: "Promiňte, jdu pozdě.", slovni_druh: "přídavné jméno" },
  // ---------- ÚROVEŇ 2: 101–200 (základní slovník) ----------
  { id: 101, en: "early", cz: "brzy, časný", vyslovnost: "érly", veta_en: "I get up early.", veta_cz: "Vstávám brzy.", slovni_druh: "přídavné jméno" },
  { id: 102, en: "big", cz: "velký", vyslovnost: "byg", veta_en: "That is a big problem.", veta_cz: "To je velký problém.", slovni_druh: "přídavné jméno" },
  { id: 103, en: "small", cz: "malý", vyslovnost: "smól", veta_en: "A small beer, please.", veta_cz: "Malé pivo, prosím.", slovni_druh: "přídavné jméno" },
  { id: 104, en: "old", cz: "starý", vyslovnost: "ould", veta_en: "This building is very old.", veta_cz: "Tahle budova je moc stará.", slovni_druh: "přídavné jméno" },
  { id: 105, en: "young", cz: "mladý", vyslovnost: "jang", veta_en: "She is still young.", veta_cz: "Je ještě mladá.", slovni_druh: "přídavné jméno" },
  { id: 106, en: "long", cz: "dlouhý", vyslovnost: "long", veta_en: "It is a long way.", veta_cz: "Je to daleko.", slovni_druh: "přídavné jméno" },
  { id: 107, en: "short", cz: "krátký", vyslovnost: "šórt", veta_en: "We take a short break.", veta_cz: "Dáme si krátkou pauzu.", slovni_druh: "přídavné jméno" },
  { id: 108, en: "high", cz: "vysoký", vyslovnost: "haj", veta_en: "The prices are high here.", veta_cz: "Ceny jsou tu vysoké.", slovni_druh: "přídavné jméno" },
  { id: 109, en: "low", cz: "nízký", vyslovnost: "lou", veta_en: "The battery is low.", veta_cz: "Baterka je skoro vybitá.", slovni_druh: "přídavné jméno" },
  { id: 110, en: "hot", cz: "horký", vyslovnost: "hot", veta_en: "The soup is too hot.", veta_cz: "Polévka je moc horká.", slovni_druh: "přídavné jméno" },
  { id: 111, en: "cold", cz: "studený, zima", vyslovnost: "kould", veta_en: "It is cold outside.", veta_cz: "Venku je zima.", slovni_druh: "přídavné jméno" },
  { id: 112, en: "nice", cz: "pěkný, milý", vyslovnost: "najs", veta_en: "It is nice to meet you.", veta_cz: "Těší mě.", slovni_druh: "přídavné jméno" },
  { id: 113, en: "bad", cz: "špatný", vyslovnost: "bed", veta_en: "The weather is bad today.", veta_cz: "Dnes je špatné počasí.", slovni_druh: "přídavné jméno" },
  { id: 114, en: "easy", cz: "snadný", vyslovnost: "ízy", veta_en: "It is not easy for me.", veta_cz: "Není to pro mě snadné.", slovni_druh: "přídavné jméno" },
  { id: 115, en: "hard", cz: "těžký, tvrdý", vyslovnost: "hárd", veta_en: "English is hard, but fun.", veta_cz: "Angličtina je těžká, ale baví mě.", slovni_druh: "přídavné jméno" },
  { id: 116, en: "happy", cz: "šťastný", vyslovnost: "hepy", veta_en: "I am happy to see you.", veta_cz: "Jsem rád, že tě vidím.", slovni_druh: "přídavné jméno" },
  { id: 117, en: "tired", cz: "unavený", vyslovnost: "tajrd", veta_en: "I am tired today.", veta_cz: "Dnes jsem unavený.", slovni_druh: "přídavné jméno" },
  { id: 118, en: "hungry", cz: "hladový", vyslovnost: "hangry", veta_en: "Are you hungry?", veta_cz: "Máš hlad?", slovni_druh: "přídavné jméno" },
  { id: 119, en: "thirsty", cz: "žíznivý", vyslovnost: "sérsty", veta_en: "I am thirsty.", veta_cz: "Mám žízeň.", slovni_druh: "přídavné jméno" },
  { id: 120, en: "sorry", cz: "promiň, je mi líto", vyslovnost: "sory", veta_en: "Sorry, I do not understand.", veta_cz: "Promiňte, nerozumím.", slovni_druh: "přídavné jméno" },
  { id: 121, en: "please", cz: "prosím", vyslovnost: "plíz", veta_en: "Two coffees, please.", veta_cz: "Dvě kávy, prosím.", slovni_druh: "fráze" },
  { id: 122, en: "thank you", cz: "děkuji", vyslovnost: "senk jů", veta_en: "Thank you very much.", veta_cz: "Moc děkuji.", slovni_druh: "fráze" },
  { id: 123, en: "yes", cz: "ano", vyslovnost: "jes", veta_en: "Yes, of course.", veta_cz: "Ano, samozřejmě.", slovni_druh: "fráze" },
  { id: 124, en: "hello", cz: "ahoj, dobrý den", vyslovnost: "helou", veta_en: "Hello, how are you?", veta_cz: "Dobrý den, jak se máte?", slovni_druh: "fráze" },
  { id: 125, en: "goodbye", cz: "na shledanou", vyslovnost: "gudbaj", veta_en: "Goodbye, see you soon.", veta_cz: "Na shledanou, brzy na viděnou.", slovni_druh: "fráze" },
  { id: 126, en: "friend", cz: "kamarád, přítel", vyslovnost: "frend", veta_en: "He is a good friend.", veta_cz: "Je to dobrý kamarád.", slovni_druh: "podstatné jméno" },
  { id: 127, en: "family", cz: "rodina", vyslovnost: "femyly", veta_en: "My family lives in Prague.", veta_cz: "Moje rodina žije v Praze.", slovni_druh: "podstatné jméno" },
  { id: 128, en: "mother", cz: "matka, maminka", vyslovnost: "madr", veta_en: "My mother is eighty.", veta_cz: "Mojí mámě je osmdesát.", slovni_druh: "podstatné jméno" },
  { id: 129, en: "father", cz: "otec, táta", vyslovnost: "fádr", veta_en: "His father is a teacher.", veta_cz: "Jeho otec je učitel.", slovni_druh: "podstatné jméno" },
  { id: 130, en: "son", cz: "syn", vyslovnost: "san", veta_en: "My son lives abroad.", veta_cz: "Můj syn žije v zahraničí.", slovni_druh: "podstatné jméno" },
  { id: 131, en: "daughter", cz: "dcera", vyslovnost: "dótr", veta_en: "My daughter is a doctor.", veta_cz: "Moje dcera je doktorka.", slovni_druh: "podstatné jméno" },
  { id: 132, en: "wife", cz: "manželka", vyslovnost: "wajf", veta_en: "This is my wife, Anna.", veta_cz: "To je moje žena Anna.", slovni_druh: "podstatné jméno" },
  { id: 133, en: "husband", cz: "manžel", vyslovnost: "hazbend", veta_en: "Her husband is from Spain.", veta_cz: "Její manžel je ze Španělska.", slovni_druh: "podstatné jméno" },
  { id: 134, en: "brother", cz: "bratr", vyslovnost: "bradr", veta_en: "I have one brother.", veta_cz: "Mám jednoho bratra.", slovni_druh: "podstatné jméno" },
  { id: 135, en: "sister", cz: "sestra", vyslovnost: "systr", veta_en: "My sister lives in Brno.", veta_cz: "Moje sestra bydlí v Brně.", slovni_druh: "podstatné jméno" },
  { id: 136, en: "need", cz: "potřebovat", vyslovnost: "níd", veta_en: "I need some help.", veta_cz: "Potřebuju pomoc.", slovni_druh: "sloveso" },
  { id: 137, en: "help", cz: "pomoct, pomoc", vyslovnost: "help", veta_en: "Can you help me, please?", veta_cz: "Můžete mi prosím pomoct?", slovni_druh: "sloveso" },
  { id: 138, en: "find", cz: "najít", vyslovnost: "fajnd", veta_en: "I cannot find my keys.", veta_cz: "Nemůžu najít klíče.", slovni_druh: "sloveso" },
  { id: 139, en: "tell", cz: "říct, povědět", vyslovnost: "tel", veta_en: "Tell me more.", veta_cz: "Řekni mi víc.", slovni_druh: "sloveso" },
  { id: 140, en: "ask", cz: "zeptat se, poprosit", vyslovnost: "ásk", veta_en: "Can I ask you something?", veta_cz: "Můžu se na něco zeptat?", slovni_druh: "sloveso" },
  { id: 141, en: "answer", cz: "odpovědět, odpověď", vyslovnost: "ánsr", veta_en: "I do not know the answer.", veta_cz: "Neznám odpověď.", slovni_druh: "sloveso" },
  { id: 142, en: "speak", cz: "mluvit", vyslovnost: "spík", veta_en: "Do you speak English?", veta_cz: "Mluvíte anglicky?", slovni_druh: "sloveso" },
  { id: 143, en: "talk", cz: "povídat si", vyslovnost: "tók", veta_en: "We need to talk.", veta_cz: "Musíme si promluvit.", slovni_druh: "sloveso" },
  { id: 144, en: "listen", cz: "poslouchat", vyslovnost: "lysn", veta_en: "Listen to this song.", veta_cz: "Poslechni si tuhle písničku.", slovni_druh: "sloveso" },
  { id: 145, en: "hear", cz: "slyšet", vyslovnost: "hír", veta_en: "I cannot hear you.", veta_cz: "Neslyším tě.", slovni_druh: "sloveso" },
  { id: 146, en: "read", cz: "číst", vyslovnost: "říd", veta_en: "I read the news every day.", veta_cz: "Každý den čtu zprávy.", slovni_druh: "sloveso" },
  { id: 147, en: "write", cz: "psát", vyslovnost: "rajt", veta_en: "Write it down, please.", veta_cz: "Napište to prosím.", slovni_druh: "sloveso" },
  { id: 148, en: "learn", cz: "učit se", vyslovnost: "lérn", veta_en: "I am learning English.", veta_cz: "Učím se anglicky.", slovni_druh: "sloveso" },
  { id: 149, en: "understand", cz: "rozumět", vyslovnost: "andrstend", veta_en: "I do not understand.", veta_cz: "Nerozumím.", slovni_druh: "sloveso" },
  { id: 150, en: "remember", cz: "pamatovat si", vyslovnost: "rymembr", veta_en: "I remember that day.", veta_cz: "Pamatuju si ten den.", slovni_druh: "sloveso" },
  { id: 151, en: "forget", cz: "zapomenout", vyslovnost: "forget", veta_en: "Do not forget your passport.", veta_cz: "Nezapomeň si pas.", slovni_druh: "sloveso" },
  { id: 152, en: "buy", cz: "koupit", vyslovnost: "baj", veta_en: "I want to buy a ticket.", veta_cz: "Chci si koupit lístek.", slovni_druh: "sloveso" },
  { id: 153, en: "pay", cz: "platit", vyslovnost: "pej", veta_en: "Can I pay by card?", veta_cz: "Můžu platit kartou?", slovni_druh: "sloveso" },
  { id: 154, en: "sell", cz: "prodat", vyslovnost: "sel", veta_en: "They sell good bread here.", veta_cz: "Prodávají tu dobrý chleba.", slovni_druh: "sloveso" },
  { id: 155, en: "cost", cz: "stát (o ceně)", vyslovnost: "kost", veta_en: "How much does it cost?", veta_cz: "Kolik to stojí?", slovni_druh: "sloveso" },
  { id: 156, en: "open", cz: "otevřít, otevřený", vyslovnost: "oupn", veta_en: "The shop is open until six.", veta_cz: "Obchod má otevřeno do šesti.", slovni_druh: "sloveso" },
  { id: 157, en: "close", cz: "zavřít; blízko", vyslovnost: "klouz", veta_en: "Please close the door.", veta_cz: "Zavřete prosím dveře.", slovni_druh: "sloveso" },
  { id: 158, en: "start", cz: "začít", vyslovnost: "start", veta_en: "The film starts at eight.", veta_cz: "Film začíná v osm.", slovni_druh: "sloveso" },
  { id: 159, en: "stop", cz: "zastavit, přestat", vyslovnost: "stop", veta_en: "Stop here, please.", veta_cz: "Zastavte tady, prosím.", slovni_druh: "sloveso" },
  { id: 160, en: "wait", cz: "čekat", vyslovnost: "wejt", veta_en: "Wait for me here.", veta_cz: "Počkej tu na mě.", slovni_druh: "sloveso" },
  { id: 161, en: "walk", cz: "jít pěšky, procházka", vyslovnost: "wók", veta_en: "Let us walk to the park.", veta_cz: "Pojďme pěšky do parku.", slovni_druh: "sloveso" },
  { id: 162, en: "run", cz: "běžet", vyslovnost: "ran", veta_en: "I run every morning.", veta_cz: "Každé ráno běhám.", slovni_druh: "sloveso" },
  { id: 163, en: "drive", cz: "řídit", vyslovnost: "drajv", veta_en: "I drive to work.", veta_cz: "Do práce jezdím autem.", slovni_druh: "sloveso" },
  { id: 164, en: "fly", cz: "letět", vyslovnost: "flaj", veta_en: "We fly to Spain tomorrow.", veta_cz: "Zítra letíme do Španělska.", slovni_druh: "sloveso" },
  { id: 165, en: "travel", cz: "cestovat", vyslovnost: "trevl", veta_en: "I like to travel.", veta_cz: "Rád cestuju.", slovni_druh: "sloveso" },
  { id: 166, en: "stay", cz: "zůstat, bydlet (dočasně)", vyslovnost: "stej", veta_en: "We stay here for three nights.", veta_cz: "Zůstáváme tu tři noci.", slovni_druh: "sloveso" },
  { id: 167, en: "leave", cz: "odejít, odjet; nechat", vyslovnost: "lív", veta_en: "The train leaves at ten.", veta_cz: "Vlak odjíždí v deset.", slovni_druh: "sloveso" },
  { id: 168, en: "arrive", cz: "přijet, dorazit", vyslovnost: "erajv", veta_en: "We arrive in the evening.", veta_cz: "Přijedeme večer.", slovni_druh: "sloveso" },
  { id: 169, en: "return", cz: "vrátit se", vyslovnost: "rytérn", veta_en: "I return on Sunday.", veta_cz: "Vracím se v neděli.", slovni_druh: "sloveso" },
  { id: 170, en: "meet", cz: "potkat, sejít se", vyslovnost: "mít", veta_en: "Let us meet at the station.", veta_cz: "Sejdeme se na nádraží.", slovni_druh: "sloveso" },
  { id: 171, en: "visit", cz: "navštívit", vyslovnost: "vyzyt", veta_en: "We visit my parents on Sunday.", veta_cz: "V neděli jedeme za rodiči.", slovni_druh: "sloveso" },
  { id: 172, en: "live", cz: "žít, bydlet", vyslovnost: "lyv", veta_en: "I live in a small town.", veta_cz: "Bydlím v malém městě.", slovni_druh: "sloveso" },
  { id: 173, en: "die", cz: "zemřít", vyslovnost: "daj", veta_en: "The plant will die without water.", veta_cz: "Bez vody ta rostlina uhyne.", slovni_druh: "sloveso" },
  { id: 174, en: "eat", cz: "jíst", vyslovnost: "ít", veta_en: "What time do we eat?", veta_cz: "V kolik jíme?", slovni_druh: "sloveso" },
  { id: 175, en: "drink", cz: "pít", vyslovnost: "drynk", veta_en: "I drink tea in the morning.", veta_cz: "Ráno piju čaj.", slovni_druh: "sloveso" },
  { id: 176, en: "cook", cz: "vařit", vyslovnost: "kuk", veta_en: "My wife cooks very well.", veta_cz: "Moje žena moc dobře vaří.", slovni_druh: "sloveso" },
  { id: 177, en: "sleep", cz: "spát", vyslovnost: "slíp", veta_en: "I sleep eight hours.", veta_cz: "Spím osm hodin.", slovni_druh: "sloveso" },
  { id: 178, en: "wake up", cz: "vzbudit se", vyslovnost: "wejk ap", veta_en: "I wake up at six.", veta_cz: "Budím se v šest.", slovni_druh: "sloveso" },
  { id: 179, en: "wash", cz: "mýt, prát", vyslovnost: "woš", veta_en: "Wash your hands, please.", veta_cz: "Umyj si prosím ruce.", slovni_druh: "sloveso" },
  { id: 180, en: "wear", cz: "nosit (oblečení)", vyslovnost: "wér", veta_en: "He wears a blue coat.", veta_cz: "Nosí modrý kabát.", slovni_druh: "sloveso" },
  { id: 181, en: "sit", cz: "sedět", vyslovnost: "syt", veta_en: "Please sit down.", veta_cz: "Posaďte se, prosím.", slovni_druh: "sloveso" },
  { id: 182, en: "stand", cz: "stát", vyslovnost: "stend", veta_en: "We stand in a queue.", veta_cz: "Stojíme ve frontě.", slovni_druh: "sloveso" },
  { id: 183, en: "put", cz: "položit, dát", vyslovnost: "put", veta_en: "Put it on the table.", veta_cz: "Polož to na stůl.", slovni_druh: "sloveso" },
  { id: 184, en: "keep", cz: "nechat si, uchovat", vyslovnost: "kíp", veta_en: "Keep the change.", veta_cz: "Nechte si drobné.", slovni_druh: "sloveso" },
  { id: 185, en: "bring", cz: "přinést", vyslovnost: "bryng", veta_en: "Bring me the menu, please.", veta_cz: "Přineste mi prosím jídelní lístek.", slovni_druh: "sloveso" },
  { id: 186, en: "send", cz: "poslat", vyslovnost: "send", veta_en: "I will send you a message.", veta_cz: "Pošlu ti zprávu.", slovni_druh: "sloveso" },
  { id: 187, en: "carry", cz: "nést", vyslovnost: "kery", veta_en: "Can you carry this bag?", veta_cz: "Uneseš tu tašku?", slovni_druh: "sloveso" },
  { id: 188, en: "hold", cz: "držet", vyslovnost: "hould", veta_en: "Hold this for a moment.", veta_cz: "Podrž to na chvíli.", slovni_druh: "sloveso" },
  { id: 189, en: "turn", cz: "otočit, zabočit", vyslovnost: "térn", veta_en: "Turn left at the corner.", veta_cz: "Na rohu zahněte doleva.", slovni_druh: "sloveso" },
  { id: 190, en: "change", cz: "změnit, vyměnit", vyslovnost: "čejndž", veta_en: "I want to change my seat.", veta_cz: "Chci si vyměnit místo.", slovni_druh: "sloveso" },
  { id: 191, en: "try", cz: "zkusit", vyslovnost: "traj", veta_en: "Try this, it is good.", veta_cz: "Zkus to, je to dobré.", slovni_druh: "sloveso" },
  { id: 192, en: "play", cz: "hrát (si)", vyslovnost: "plej", veta_en: "The children play outside.", veta_cz: "Děti si hrají venku.", slovni_druh: "sloveso" },
  { id: 193, en: "win", cz: "vyhrát", vyslovnost: "wyn", veta_en: "I want to win.", veta_cz: "Chci vyhrát.", slovni_druh: "sloveso" },
  { id: 194, en: "lose", cz: "prohrát, ztratit", vyslovnost: "lúz", veta_en: "Do not lose the key.", veta_cz: "Neztrať ten klíč.", slovni_druh: "sloveso" },
  { id: 195, en: "begin", cz: "začít", vyslovnost: "bygyn", veta_en: "Let us begin.", veta_cz: "Začněme.", slovni_druh: "sloveso" },
  { id: 196, en: "finish", cz: "dokončit, skončit", vyslovnost: "fynyš", veta_en: "I finish work at five.", veta_cz: "Končím v práci v pět.", slovni_druh: "sloveso" },
  { id: 197, en: "build", cz: "postavit", vyslovnost: "byld", veta_en: "They build a new house.", veta_cz: "Staví nový dům.", slovni_druh: "sloveso" },
  { id: 198, en: "break", cz: "rozbít, zlomit", vyslovnost: "brejk", veta_en: "Careful, you will break it.", veta_cz: "Opatrně, rozbiješ to.", slovni_druh: "sloveso" },
  { id: 199, en: "fix", cz: "spravit", vyslovnost: "fyks", veta_en: "Can you fix my watch?", veta_cz: "Můžete mi spravit hodinky?", slovni_druh: "sloveso" },
  { id: 200, en: "clean", cz: "uklidit; čistý", vyslovnost: "klín", veta_en: "The room is clean.", veta_cz: "Pokoj je čistý.", slovni_druh: "sloveso" },
  // ---------- ÚROVEŇ 3: 201–300 (běžná slovesa a věci kolem nás) ----------
  { id: 201, en: "cut", cz: "řezat, krájet", vyslovnost: "kat", veta_en: "Cut the bread, please.", veta_cz: "Nakrájej prosím chleba.", slovni_druh: "sloveso" },
  { id: 202, en: "fall", cz: "spadnout", vyslovnost: "fól", veta_en: "Be careful, do not fall.", veta_cz: "Dávej pozor, ať nespadneš.", slovni_druh: "sloveso" },
  { id: 203, en: "feel", cz: "cítit se", vyslovnost: "fíl", veta_en: "I feel much better.", veta_cz: "Cítím se mnohem líp.", slovni_druh: "sloveso" },
  { id: 204, en: "love", cz: "milovat, mít moc rád", vyslovnost: "lav", veta_en: "I love this place.", veta_cz: "Tohle místo mám moc rád.", slovni_druh: "sloveso" },
  { id: 205, en: "hope", cz: "doufat", vyslovnost: "houp", veta_en: "I hope you are well.", veta_cz: "Doufám, že se ti daří.", slovni_druh: "sloveso" },
  { id: 206, en: "believe", cz: "věřit", vyslovnost: "bylív", veta_en: "I do not believe it.", veta_cz: "Tomu nevěřím.", slovni_druh: "sloveso" },
  { id: 207, en: "seem", cz: "zdát se", vyslovnost: "sím", veta_en: "It seems easy.", veta_cz: "Vypadá to snadně.", slovni_druh: "sloveso" },
  { id: 208, en: "become", cz: "stát se (čím)", vyslovnost: "bykam", veta_en: "He became a doctor.", veta_cz: "Stal se doktorem.", slovni_druh: "sloveso" },
  { id: 209, en: "happen", cz: "stát se, přihodit se", vyslovnost: "hepn", veta_en: "What happens now?", veta_cz: "Co se stane teď?", slovni_druh: "sloveso" },
  { id: 210, en: "mean", cz: "znamenat", vyslovnost: "mín", veta_en: "What does this word mean?", veta_cz: "Co to slovo znamená?", slovni_druh: "sloveso" },
  { id: 211, en: "call", cz: "zavolat; nazývat", vyslovnost: "kól", veta_en: "Call me later.", veta_cz: "Zavolej mi později.", slovni_druh: "sloveso" },
  { id: 212, en: "show", cz: "ukázat", vyslovnost: "šou", veta_en: "Show me on the map.", veta_cz: "Ukažte mi to na mapě.", slovni_druh: "sloveso" },
  { id: 213, en: "watch", cz: "dívat se; hodinky", vyslovnost: "woč", veta_en: "We watch the news at seven.", veta_cz: "V sedm se díváme na zprávy.", slovni_druh: "sloveso" },
  { id: 214, en: "choose", cz: "vybrat si", vyslovnost: "čúz", veta_en: "You can choose.", veta_cz: "Můžeš si vybrat.", slovni_druh: "sloveso" },
  { id: 215, en: "decide", cz: "rozhodnout se", vyslovnost: "dysajd", veta_en: "We decide tomorrow.", veta_cz: "Rozhodneme se zítra.", slovni_druh: "sloveso" },
  { id: 216, en: "explain", cz: "vysvětlit", vyslovnost: "yksplejn", veta_en: "Can you explain it again?", veta_cz: "Můžete to vysvětlit znovu?", slovni_druh: "sloveso" },
  { id: 217, en: "follow", cz: "následovat, jít za", vyslovnost: "folou", veta_en: "Follow me, please.", veta_cz: "Pojďte za mnou, prosím.", slovni_druh: "sloveso" },
  { id: 218, en: "continue", cz: "pokračovat", vyslovnost: "kentynjů", veta_en: "Continue straight ahead.", veta_cz: "Pokračujte rovně.", slovni_druh: "sloveso" },
  { id: 219, en: "move", cz: "pohnout se, stěhovat se", vyslovnost: "múv", veta_en: "We move to a new flat.", veta_cz: "Stěhujeme se do nového bytu.", slovni_druh: "sloveso" },
  { id: 220, en: "add", cz: "přidat", vyslovnost: "ed", veta_en: "Add some salt.", veta_cz: "Přidej trochu soli.", slovni_druh: "sloveso" },
  { id: 221, en: "check", cz: "zkontrolovat", vyslovnost: "ček", veta_en: "Check the time, please.", veta_cz: "Zkontroluj prosím čas.", slovni_druh: "sloveso" },
  { id: 222, en: "table", cz: "stůl", vyslovnost: "tejbl", veta_en: "A table for two, please.", veta_cz: "Stůl pro dva, prosím.", slovni_druh: "podstatné jméno" },
  { id: 223, en: "chair", cz: "židle", vyslovnost: "čér", veta_en: "Take a chair.", veta_cz: "Vezmi si židli.", slovni_druh: "podstatné jméno" },
  { id: 224, en: "door", cz: "dveře", vyslovnost: "dór", veta_en: "The door is locked.", veta_cz: "Dveře jsou zamčené.", slovni_druh: "podstatné jméno" },
  { id: 225, en: "window", cz: "okno", vyslovnost: "wyndou", veta_en: "Open the window, please.", veta_cz: "Otevřete prosím okno.", slovni_druh: "podstatné jméno" },
  { id: 226, en: "bed", cz: "postel", vyslovnost: "bed", veta_en: "The bed is comfortable.", veta_cz: "Postel je pohodlná.", slovni_druh: "podstatné jméno" },
  { id: 227, en: "kitchen", cz: "kuchyně", vyslovnost: "kyčn", veta_en: "She is in the kitchen.", veta_cz: "Je v kuchyni.", slovni_druh: "podstatné jméno" },
  { id: 228, en: "bathroom", cz: "koupelna, záchod", vyslovnost: "básrúm", veta_en: "Where is the bathroom?", veta_cz: "Kde je koupelna?", slovni_druh: "podstatné jméno" },
  { id: 229, en: "street", cz: "ulice", vyslovnost: "strít", veta_en: "We live on this street.", veta_cz: "Bydlíme v téhle ulici.", slovni_druh: "podstatné jméno" },
  { id: 230, en: "shop", cz: "obchod", vyslovnost: "šop", veta_en: "The shop is closed.", veta_cz: "Obchod je zavřený.", slovni_druh: "podstatné jméno" },
  { id: 231, en: "market", cz: "trh", vyslovnost: "márkyt", veta_en: "We buy fruit at the market.", veta_cz: "Ovoce kupujeme na trhu.", slovni_druh: "podstatné jméno" },
  { id: 232, en: "restaurant", cz: "restaurace", vyslovnost: "restront", veta_en: "I know a good restaurant.", veta_cz: "Znám dobrou restauraci.", slovni_druh: "podstatné jméno" },
  { id: 233, en: "hotel", cz: "hotel", vyslovnost: "houtel", veta_en: "Our hotel is near the beach.", veta_cz: "Náš hotel je blízko pláže.", slovni_druh: "podstatné jméno" },
  { id: 234, en: "station", cz: "nádraží, stanice", vyslovnost: "stejšn", veta_en: "The station is over there.", veta_cz: "Nádraží je tamhle.", slovni_druh: "podstatné jméno" },
  { id: 235, en: "airport", cz: "letiště", vyslovnost: "érport", veta_en: "We go to the airport at five.", veta_cz: "V pět jedeme na letiště.", slovni_druh: "podstatné jméno" },
  { id: 236, en: "train", cz: "vlak", vyslovnost: "trejn", veta_en: "The train is late.", veta_cz: "Vlak má zpoždění.", slovni_druh: "podstatné jméno" },
  { id: 237, en: "bus", cz: "autobus", vyslovnost: "bas", veta_en: "Which bus goes downtown?", veta_cz: "Který autobus jede do centra?", slovni_druh: "podstatné jméno" },
  { id: 238, en: "plane", cz: "letadlo", vyslovnost: "plejn", veta_en: "The plane leaves at noon.", veta_cz: "Letadlo odlétá v poledne.", slovni_druh: "podstatné jméno" },
  { id: 239, en: "ticket", cz: "lístek, jízdenka", vyslovnost: "tykyt", veta_en: "Two tickets to London, please.", veta_cz: "Dva lístky do Londýna, prosím.", slovni_druh: "podstatné jméno" },
  { id: 240, en: "bag", cz: "taška, kufr", vyslovnost: "beg", veta_en: "This bag is heavy.", veta_cz: "Ta taška je těžká.", slovni_druh: "podstatné jméno" },
  { id: 241, en: "key", cz: "klíč", vyslovnost: "kí", veta_en: "Here is your room key.", veta_cz: "Tady je klíč od pokoje.", slovni_druh: "podstatné jméno" },
  { id: 242, en: "phone", cz: "telefon", vyslovnost: "foun", veta_en: "My phone is not working.", veta_cz: "Můj telefon nefunguje.", slovni_druh: "podstatné jméno" },
  { id: 243, en: "computer", cz: "počítač", vyslovnost: "kempjútr", veta_en: "The computer is slow.", veta_cz: "Počítač je pomalý.", slovni_druh: "podstatné jméno" },
  { id: 244, en: "book", cz: "kniha; rezervovat", vyslovnost: "buk", veta_en: "I want to book a room.", veta_cz: "Chci si rezervovat pokoj.", slovni_druh: "podstatné jméno" },
  { id: 245, en: "paper", cz: "papír", vyslovnost: "pejpr", veta_en: "I need a piece of paper.", veta_cz: "Potřebuju kus papíru.", slovni_druh: "podstatné jméno" },
  { id: 246, en: "letter", cz: "dopis; písmeno", vyslovnost: "letr", veta_en: "This letter is for you.", veta_cz: "Tenhle dopis je pro tebe.", slovni_druh: "podstatné jméno" },
  { id: 247, en: "word", cz: "slovo", vyslovnost: "wérd", veta_en: "I do not know this word.", veta_cz: "Tohle slovo neznám.", slovni_druh: "podstatné jméno" },
  { id: 248, en: "question", cz: "otázka", vyslovnost: "kwesčn", veta_en: "That is a good question.", veta_cz: "To je dobrá otázka.", slovni_druh: "podstatné jméno" },
  { id: 249, en: "problem", cz: "problém", vyslovnost: "problem", veta_en: "No problem.", veta_cz: "Žádný problém.", slovni_druh: "podstatné jméno" },
  { id: 250, en: "idea", cz: "nápad", vyslovnost: "ajdýe", veta_en: "That is a great idea.", veta_cz: "To je skvělý nápad.", slovni_druh: "podstatné jméno" },
  { id: 251, en: "story", cz: "příběh", vyslovnost: "stóry", veta_en: "Tell me the whole story.", veta_cz: "Pověz mi celý příběh.", slovni_druh: "podstatné jméno" },
  { id: 252, en: "school", cz: "škola", vyslovnost: "skúl", veta_en: "The children are at school.", veta_cz: "Děti jsou ve škole.", slovni_druh: "podstatné jméno" },
  { id: 253, en: "job", cz: "práce, zaměstnání", vyslovnost: "džob", veta_en: "He has a new job.", veta_cz: "Má novou práci.", slovni_druh: "podstatné jméno" },
  { id: 254, en: "office", cz: "kancelář", vyslovnost: "ofys", veta_en: "I am in the office until four.", veta_cz: "Jsem v kanceláři do čtyř.", slovni_druh: "podstatné jméno" },
  { id: 255, en: "company", cz: "firma", vyslovnost: "kampeny", veta_en: "She works for a big company.", veta_cz: "Pracuje pro velkou firmu.", slovni_druh: "podstatné jméno" },
  { id: 256, en: "business", cz: "podnikání, obchod", vyslovnost: "byznys", veta_en: "I am here on business.", veta_cz: "Jsem tu pracovně.", slovni_druh: "podstatné jméno" },
  { id: 257, en: "doctor", cz: "lékař", vyslovnost: "doktr", veta_en: "I need a doctor.", veta_cz: "Potřebuju doktora.", slovni_druh: "podstatné jméno" },
  { id: 258, en: "hospital", cz: "nemocnice", vyslovnost: "hospytl", veta_en: "The hospital is close.", veta_cz: "Nemocnice je blízko.", slovni_druh: "podstatné jméno" },
  { id: 259, en: "medicine", cz: "lék", vyslovnost: "medsn", veta_en: "I take this medicine every day.", veta_cz: "Tenhle lék beru každý den.", slovni_druh: "podstatné jméno" },
  { id: 260, en: "health", cz: "zdraví", vyslovnost: "hels", veta_en: "Health is the most important thing.", veta_cz: "Zdraví je nejdůležitější.", slovni_druh: "podstatné jméno" },
  { id: 261, en: "body", cz: "tělo", vyslovnost: "body", veta_en: "My whole body hurts.", veta_cz: "Bolí mě celé tělo.", slovni_druh: "podstatné jméno" },
  { id: 262, en: "head", cz: "hlava", vyslovnost: "hed", veta_en: "My head hurts.", veta_cz: "Bolí mě hlava.", slovni_druh: "podstatné jméno" },
  { id: 263, en: "hand", cz: "ruka", vyslovnost: "hend", veta_en: "Give me your hand.", veta_cz: "Podej mi ruku.", slovni_druh: "podstatné jméno" },
  { id: 264, en: "eye", cz: "oko", vyslovnost: "aj", veta_en: "She has blue eyes.", veta_cz: "Má modré oči.", slovni_druh: "podstatné jméno" },
  { id: 265, en: "foot", cz: "chodidlo, noha", vyslovnost: "fut", veta_en: "We go on foot.", veta_cz: "Jdeme pěšky.", slovni_druh: "podstatné jméno" },
  { id: 266, en: "heart", cz: "srdce", vyslovnost: "hárt", veta_en: "My heart is fine.", veta_cz: "Srdce mám v pořádku.", slovni_druh: "podstatné jméno" },
  { id: 267, en: "face", cz: "obličej", vyslovnost: "fejs", veta_en: "I know that face.", veta_cz: "Ten obličej znám.", slovni_druh: "podstatné jméno" },
  { id: 268, en: "hair", cz: "vlasy", vyslovnost: "hér", veta_en: "He has grey hair.", veta_cz: "Má šedivé vlasy.", slovni_druh: "podstatné jméno" },
  { id: 269, en: "arm", cz: "paže", vyslovnost: "árm", veta_en: "My arm is broken.", veta_cz: "Mám zlomenou ruku.", slovni_druh: "podstatné jméno" },
  { id: 270, en: "leg", cz: "noha", vyslovnost: "leg", veta_en: "My legs are tired.", veta_cz: "Bolí mě nohy.", slovni_druh: "podstatné jméno" },
  { id: 271, en: "tooth", cz: "zub", vyslovnost: "tús", veta_en: "I have a bad tooth.", veta_cz: "Mám špatný zub.", slovni_druh: "podstatné jméno" },
  { id: 272, en: "bread", cz: "chleba", vyslovnost: "bred", veta_en: "We need fresh bread.", veta_cz: "Potřebujeme čerstvý chleba.", slovni_druh: "podstatné jméno" },
  { id: 273, en: "meat", cz: "maso", vyslovnost: "mít", veta_en: "I do not eat meat.", veta_cz: "Nejím maso.", slovni_druh: "podstatné jméno" },
  { id: 274, en: "fish", cz: "ryba", vyslovnost: "fyš", veta_en: "The fish here is fresh.", veta_cz: "Ryba je tu čerstvá.", slovni_druh: "podstatné jméno" },
  { id: 275, en: "egg", cz: "vejce", vyslovnost: "eg", veta_en: "Two eggs, please.", veta_cz: "Dvě vejce, prosím.", slovni_druh: "podstatné jméno" },
  { id: 276, en: "milk", cz: "mléko", vyslovnost: "mylk", veta_en: "Coffee with milk, please.", veta_cz: "Kávu s mlékem, prosím.", slovni_druh: "podstatné jméno" },
  { id: 277, en: "cheese", cz: "sýr", vyslovnost: "číz", veta_en: "This cheese is very good.", veta_cz: "Tenhle sýr je moc dobrý.", slovni_druh: "podstatné jméno" },
  { id: 278, en: "fruit", cz: "ovoce", vyslovnost: "frút", veta_en: "I eat fruit every day.", veta_cz: "Každý den jím ovoce.", slovni_druh: "podstatné jméno" },
  { id: 279, en: "apple", cz: "jablko", vyslovnost: "epl", veta_en: "An apple a day.", veta_cz: "Jedno jablko denně.", slovni_druh: "podstatné jméno" },
  { id: 280, en: "vegetable", cz: "zelenina", vyslovnost: "vedžtebl", veta_en: "We grow vegetables in the garden.", veta_cz: "Pěstujeme na zahradě zeleninu.", slovni_druh: "podstatné jméno" },
  { id: 281, en: "potato", cz: "brambora", vyslovnost: "petejtou", veta_en: "Potatoes with butter.", veta_cz: "Brambory s máslem.", slovni_druh: "podstatné jméno" },
  { id: 282, en: "rice", cz: "rýže", vyslovnost: "rajs", veta_en: "Chicken with rice, please.", veta_cz: "Kuře s rýží, prosím.", slovni_druh: "podstatné jméno" },
  { id: 283, en: "soup", cz: "polévka", vyslovnost: "súp", veta_en: "The soup is cold.", veta_cz: "Polévka je studená.", slovni_druh: "podstatné jméno" },
  { id: 284, en: "salt", cz: "sůl", vyslovnost: "sólt", veta_en: "Pass me the salt, please.", veta_cz: "Podej mi prosím sůl.", slovni_druh: "podstatné jméno" },
  { id: 285, en: "sugar", cz: "cukr", vyslovnost: "šugr", veta_en: "No sugar in my tea.", veta_cz: "Do čaje cukr nechci.", slovni_druh: "podstatné jméno" },
  { id: 286, en: "coffee", cz: "káva", vyslovnost: "kofy", veta_en: "One coffee, please.", veta_cz: "Jednu kávu, prosím.", slovni_druh: "podstatné jméno" },
  { id: 287, en: "tea", cz: "čaj", vyslovnost: "tí", veta_en: "I drink tea in the evening.", veta_cz: "Večer piju čaj.", slovni_druh: "podstatné jméno" },
  { id: 288, en: "beer", cz: "pivo", vyslovnost: "bír", veta_en: "Czech beer is famous.", veta_cz: "České pivo je slavné.", slovni_druh: "podstatné jméno" },
  { id: 289, en: "wine", cz: "víno", vyslovnost: "wajn", veta_en: "A glass of red wine.", veta_cz: "Sklenku červeného vína.", slovni_druh: "podstatné jméno" },
  { id: 290, en: "breakfast", cz: "snídaně", vyslovnost: "brekfest", veta_en: "Breakfast is at eight.", veta_cz: "Snídaně je v osm.", slovni_druh: "podstatné jméno" },
  { id: 291, en: "lunch", cz: "oběd", vyslovnost: "lanč", veta_en: "Let us have lunch together.", veta_cz: "Pojďme na oběd spolu.", slovni_druh: "podstatné jméno" },
  { id: 292, en: "dinner", cz: "večeře", vyslovnost: "dynr", veta_en: "Dinner is ready.", veta_cz: "Večeře je hotová.", slovni_druh: "podstatné jméno" },
  { id: 293, en: "menu", cz: "jídelní lístek", vyslovnost: "menjů", veta_en: "Can I see the menu?", veta_cz: "Můžu dostat jídelní lístek?", slovni_druh: "podstatné jméno" },
  { id: 294, en: "bill", cz: "účet", vyslovnost: "byl", veta_en: "The bill, please.", veta_cz: "Účet, prosím.", slovni_druh: "podstatné jméno" },
  { id: 295, en: "glass", cz: "sklenice, sklo", vyslovnost: "glás", veta_en: "Another glass, please.", veta_cz: "Ještě jednu sklenici, prosím.", slovni_druh: "podstatné jméno" },
  { id: 296, en: "cup", cz: "hrnek, šálek", vyslovnost: "kap", veta_en: "A cup of tea.", veta_cz: "Šálek čaje.", slovni_druh: "podstatné jméno" },
  { id: 297, en: "plate", cz: "talíř", vyslovnost: "plejt", veta_en: "The plate is hot.", veta_cz: "Ten talíř je horký.", slovni_druh: "podstatné jméno" },
  { id: 298, en: "knife", cz: "nůž", vyslovnost: "najf", veta_en: "I need a knife.", veta_cz: "Potřebuju nůž.", slovni_druh: "podstatné jméno" },
  { id: 299, en: "fork", cz: "vidlička", vyslovnost: "fórk", veta_en: "Can I have a fork?", veta_cz: "Můžu dostat vidličku?", slovni_druh: "podstatné jméno" },
  { id: 300, en: "spoon", cz: "lžíce", vyslovnost: "spún", veta_en: "The spoon is dirty.", veta_cz: "Ta lžíce je špinavá.", slovni_druh: "podstatné jméno" },
  // ---------- ÚROVEŇ 4: 301–400 (tělo, jídlo, příroda, cestování) ----------
  { id: 301, en: "bottle", cz: "láhev", vyslovnost: "botl", veta_en: "A bottle of water, please.", veta_cz: "Láhev vody, prosím.", slovni_druh: "podstatné jméno" },
  { id: 302, en: "weather", cz: "počasí", vyslovnost: "wedr", veta_en: "The weather is nice today.", veta_cz: "Dnes je hezky.", slovni_druh: "podstatné jméno" },
  { id: 303, en: "rain", cz: "déšť, pršet", vyslovnost: "rejn", veta_en: "It is going to rain.", veta_cz: "Bude pršet.", slovni_druh: "podstatné jméno" },
  { id: 304, en: "snow", cz: "sníh, sněžit", vyslovnost: "snou", veta_en: "There is snow in the mountains.", veta_cz: "Na horách je sníh.", slovni_druh: "podstatné jméno" },
  { id: 305, en: "sun", cz: "slunce", vyslovnost: "san", veta_en: "The sun is strong today.", veta_cz: "Slunce dnes pálí.", slovni_druh: "podstatné jméno" },
  { id: 306, en: "wind", cz: "vítr", vyslovnost: "wynd", veta_en: "The wind is cold.", veta_cz: "Vítr je studený.", slovni_druh: "podstatné jméno" },
  { id: 307, en: "sky", cz: "obloha", vyslovnost: "skaj", veta_en: "The sky is clear.", veta_cz: "Obloha je jasná.", slovni_druh: "podstatné jméno" },
  { id: 308, en: "sea", cz: "moře", vyslovnost: "sí", veta_en: "I want to see the sea again.", veta_cz: "Chci zase vidět moře.", slovni_druh: "podstatné jméno" },
  { id: 309, en: "mountain", cz: "hora", vyslovnost: "mauntyn", veta_en: "We walk in the mountains.", veta_cz: "Chodíme po horách.", slovni_druh: "podstatné jméno" },
  { id: 310, en: "river", cz: "řeka", vyslovnost: "rivr", veta_en: "The river is deep here.", veta_cz: "Řeka je tu hluboká.", slovni_druh: "podstatné jméno" },
  { id: 311, en: "forest", cz: "les", vyslovnost: "forest", veta_en: "We walk in the forest.", veta_cz: "Chodíme do lesa.", slovni_druh: "podstatné jméno" },
  { id: 312, en: "tree", cz: "strom", vyslovnost: "trí", veta_en: "That tree is very old.", veta_cz: "Ten strom je hodně starý.", slovni_druh: "podstatné jméno" },
  { id: 313, en: "flower", cz: "květina", vyslovnost: "flaur", veta_en: "These flowers are for you.", veta_cz: "Tyhle květiny jsou pro tebe.", slovni_druh: "podstatné jméno" },
  { id: 314, en: "animal", cz: "zvíře", vyslovnost: "enyml", veta_en: "I like animals.", veta_cz: "Mám rád zvířata.", slovni_druh: "podstatné jméno" },
  { id: 315, en: "dog", cz: "pes", vyslovnost: "dog", veta_en: "The dog is friendly.", veta_cz: "Ten pes je přátelský.", slovni_druh: "podstatné jméno" },
  { id: 316, en: "cat", cz: "kočka", vyslovnost: "ket", veta_en: "We have a cat at home.", veta_cz: "Doma máme kočku.", slovni_druh: "podstatné jméno" },
  { id: 317, en: "bird", cz: "pták", vyslovnost: "bérd", veta_en: "The birds wake me up.", veta_cz: "Ptáci mě budí.", slovni_druh: "podstatné jméno" },
  { id: 318, en: "garden", cz: "zahrada", vyslovnost: "gárdn", veta_en: "We sit in the garden.", veta_cz: "Sedíme na zahradě.", slovni_druh: "podstatné jméno" },
  { id: 319, en: "park", cz: "park; parkovat", vyslovnost: "párk", veta_en: "Where can I park?", veta_cz: "Kde můžu zaparkovat?", slovni_druh: "podstatné jméno" },
  { id: 320, en: "road", cz: "silnice, cesta", vyslovnost: "roud", veta_en: "The road is closed.", veta_cz: "Silnice je uzavřená.", slovni_druh: "podstatné jméno" },
  { id: 321, en: "bridge", cz: "most", vyslovnost: "brydž", veta_en: "Go over the bridge.", veta_cz: "Jděte přes most.", slovni_druh: "podstatné jméno" },
  { id: 322, en: "map", cz: "mapa", vyslovnost: "mep", veta_en: "Do you have a map?", veta_cz: "Máte mapu?", slovni_druh: "podstatné jméno" },
  { id: 323, en: "border", cz: "hranice", vyslovnost: "bórdr", veta_en: "We cross the border at noon.", veta_cz: "Hranice přejedeme v poledne.", slovni_druh: "podstatné jméno" },
  { id: 324, en: "passport", cz: "pas", vyslovnost: "pásport", veta_en: "Your passport, please.", veta_cz: "Váš pas, prosím.", slovni_druh: "podstatné jméno" },
  { id: 325, en: "luggage", cz: "zavazadla", vyslovnost: "lagydž", veta_en: "Where is my luggage?", veta_cz: "Kde je moje zavazadlo?", slovni_druh: "podstatné jméno" },
  { id: 326, en: "seat", cz: "sedadlo, místo", vyslovnost: "sít", veta_en: "Is this seat free?", veta_cz: "Je tu volno?", slovni_druh: "podstatné jméno" },
  { id: 327, en: "flight", cz: "let", vyslovnost: "flajt", veta_en: "Our flight is delayed.", veta_cz: "Náš let má zpoždění.", slovni_druh: "podstatné jméno" },
  { id: 328, en: "trip", cz: "výlet, cesta", vyslovnost: "tryp", veta_en: "Have a good trip.", veta_cz: "Šťastnou cestu.", slovni_druh: "podstatné jméno" },
  { id: 329, en: "holiday", cz: "dovolená, svátek", vyslovnost: "holydej", veta_en: "We are on holiday.", veta_cz: "Jsme na dovolené.", slovni_druh: "podstatné jméno" },
  { id: 330, en: "weekend", cz: "víkend", vyslovnost: "wíkend", veta_en: "Have a nice weekend.", veta_cz: "Hezký víkend.", slovni_druh: "podstatné jméno" },
  { id: 331, en: "birthday", cz: "narozeniny", vyslovnost: "bérsdej", veta_en: "Happy birthday!", veta_cz: "Všechno nejlepší!", slovni_druh: "podstatné jméno" },
  { id: 332, en: "life", cz: "život", vyslovnost: "lajf", veta_en: "That is life.", veta_cz: "Takový je život.", slovni_druh: "podstatné jméno" },
  { id: 333, en: "world", cz: "svět", vyslovnost: "wérld", veta_en: "He travelled around the world.", veta_cz: "Objel svět.", slovni_druh: "podstatné jméno" },
  { id: 334, en: "part", cz: "část", vyslovnost: "párt", veta_en: "This is the best part.", veta_cz: "Tohle je ta nejlepší část.", slovni_druh: "podstatné jméno" },
  { id: 335, en: "number", cz: "číslo", vyslovnost: "nambr", veta_en: "What is your phone number?", veta_cz: "Jaké máte telefonní číslo?", slovni_druh: "podstatné jméno" },
  { id: 336, en: "price", cz: "cena", vyslovnost: "prajs", veta_en: "The price is too high.", veta_cz: "Cena je moc vysoká.", slovni_druh: "podstatné jméno" },
  { id: 337, en: "size", cz: "velikost", vyslovnost: "sajz", veta_en: "Do you have a bigger size?", veta_cz: "Máte větší velikost?", slovni_druh: "podstatné jméno" },
  { id: 338, en: "colour", cz: "barva", vyslovnost: "kalr", veta_en: "What colour is your car?", veta_cz: "Jakou barvu má vaše auto?", slovni_druh: "podstatné jméno" },
  { id: 339, en: "side", cz: "strana", vyslovnost: "sajd", veta_en: "It is on the other side.", veta_cz: "Je to na druhé straně.", slovni_druh: "podstatné jméno" },
  { id: 340, en: "end", cz: "konec", vyslovnost: "end", veta_en: "At the end of the street.", veta_cz: "Na konci ulice.", slovni_druh: "podstatné jméno" },
  { id: 341, en: "beginning", cz: "začátek", vyslovnost: "bygynyng", veta_en: "From the beginning, please.", veta_cz: "Od začátku, prosím.", slovni_druh: "podstatné jméno" },
  { id: 342, en: "reason", cz: "důvod", vyslovnost: "rízn", veta_en: "There is no reason to worry.", veta_cz: "Není důvod se bát.", slovni_druh: "podstatné jméno" },
  { id: 343, en: "example", cz: "příklad", vyslovnost: "ygzámpl", veta_en: "For example, this one.", veta_cz: "Například tenhle.", slovni_druh: "podstatné jméno" },
  { id: 344, en: "chance", cz: "šance, možnost", vyslovnost: "čáns", veta_en: "Give me one more chance.", veta_cz: "Dej mi ještě jednu šanci.", slovni_druh: "podstatné jméno" },
  { id: 345, en: "mistake", cz: "chyba", vyslovnost: "mystejk", veta_en: "It is my mistake.", veta_cz: "Je to moje chyba.", slovni_druh: "podstatné jméno" },
  { id: 346, en: "news", cz: "zprávy", vyslovnost: "njúz", veta_en: "I watch the news every evening.", veta_cz: "Každý večer se dívám na zprávy.", slovni_druh: "podstatné jméno" },
  { id: 347, en: "information", cz: "informace", vyslovnost: "ynfrmejšn", veta_en: "I need more information.", veta_cz: "Potřebuju víc informací.", slovni_druh: "podstatné jméno" },
  { id: 348, en: "message", cz: "zpráva, vzkaz", vyslovnost: "mesydž", veta_en: "I send you a message.", veta_cz: "Pošlu ti zprávu.", slovni_druh: "podstatné jméno" },
  { id: 349, en: "picture", cz: "obrázek, fotka", vyslovnost: "pykčr", veta_en: "Can you take a picture?", veta_cz: "Můžeš vyfotit?", slovni_druh: "podstatné jméno" },
  { id: 350, en: "music", cz: "hudba", vyslovnost: "mjúzyk", veta_en: "I like old music.", veta_cz: "Mám rád starou hudbu.", slovni_druh: "podstatné jméno" },
  { id: 351, en: "film", cz: "film", vyslovnost: "fylm", veta_en: "The film is very good.", veta_cz: "Ten film je moc dobrý.", slovni_druh: "podstatné jméno" },
  { id: 352, en: "game", cz: "hra, zápas", vyslovnost: "gejm", veta_en: "The game starts at eight.", veta_cz: "Zápas začíná v osm.", slovni_druh: "podstatné jméno" },
  { id: 353, en: "sport", cz: "sport", vyslovnost: "sport", veta_en: "Which sport do you like?", veta_cz: "Jaký sport máte rád?", slovni_druh: "podstatné jméno" },
  { id: 354, en: "team", cz: "tým", vyslovnost: "tím", veta_en: "My team is good.", veta_cz: "Můj tým je dobrý.", slovni_druh: "podstatné jméno" },
  { id: 355, en: "party", cz: "oslava, večírek", vyslovnost: "párty", veta_en: "We are having a party.", veta_cz: "Máme oslavu.", slovni_druh: "podstatné jméno" },
  { id: 356, en: "gift", cz: "dárek", vyslovnost: "gyft", veta_en: "This is a gift for you.", veta_cz: "Tohle je dárek pro tebe.", slovni_druh: "podstatné jméno" },
  { id: 357, en: "clothes", cz: "oblečení", vyslovnost: "klouz", veta_en: "I need warm clothes.", veta_cz: "Potřebuju teplé oblečení.", slovni_druh: "podstatné jméno" },
  { id: 358, en: "shoe", cz: "bota", vyslovnost: "šů", veta_en: "These shoes are too small.", veta_cz: "Tyhle boty jsou moc malé.", slovni_druh: "podstatné jméno" },
  { id: 359, en: "shirt", cz: "košile", vyslovnost: "šért", veta_en: "I need a clean shirt.", veta_cz: "Potřebuju čistou košili.", slovni_druh: "podstatné jméno" },
  { id: 360, en: "coat", cz: "kabát", vyslovnost: "kout", veta_en: "Take your coat, it is cold.", veta_cz: "Vezmi si kabát, je zima.", slovni_druh: "podstatné jméno" },
  { id: 361, en: "hat", cz: "čepice, klobouk", vyslovnost: "het", veta_en: "Where is my hat?", veta_cz: "Kde mám čepici?", slovni_druh: "podstatné jméno" },
  { id: 362, en: "beautiful", cz: "krásný", vyslovnost: "bjútyfl", veta_en: "What a beautiful day.", veta_cz: "To je krásný den.", slovni_druh: "přídavné jméno" },
  { id: 363, en: "ugly", cz: "ošklivý", vyslovnost: "agly", veta_en: "That building is ugly.", veta_cz: "Ta budova je ošklivá.", slovni_druh: "přídavné jméno" },
  { id: 364, en: "dirty", cz: "špinavý", vyslovnost: "dérty", veta_en: "My shoes are dirty.", veta_cz: "Mám špinavé boty.", slovni_druh: "přídavné jméno" },
  { id: 365, en: "full", cz: "plný", vyslovnost: "ful", veta_en: "The bus is full.", veta_cz: "Autobus je plný.", slovni_druh: "přídavné jméno" },
  { id: 366, en: "empty", cz: "prázdný", vyslovnost: "empty", veta_en: "The glass is empty.", veta_cz: "Sklenice je prázdná.", slovni_druh: "přídavné jméno" },
  { id: 367, en: "free", cz: "volný, zdarma", vyslovnost: "frí", veta_en: "Is this table free?", veta_cz: "Je tenhle stůl volný?", slovni_druh: "přídavné jméno" },
  { id: 368, en: "busy", cz: "zaneprázdněný, rušný", vyslovnost: "byzy", veta_en: "I am busy this week.", veta_cz: "Tenhle týden mám hodně práce.", slovni_druh: "přídavné jméno" },
  { id: 369, en: "expensive", cz: "drahý", vyslovnost: "ykspensyv", veta_en: "It is too expensive.", veta_cz: "Je to moc drahé.", slovni_druh: "přídavné jméno" },
  { id: 370, en: "cheap", cz: "levný", vyslovnost: "číp", veta_en: "The tickets are cheap.", veta_cz: "Lístky jsou levné.", slovni_druh: "přídavné jméno" },
  { id: 371, en: "rich", cz: "bohatý", vyslovnost: "ryč", veta_en: "He is not rich, but happy.", veta_cz: "Není bohatý, ale je šťastný.", slovni_druh: "přídavné jméno" },
  { id: 372, en: "poor", cz: "chudý", vyslovnost: "púr", veta_en: "The family is poor.", veta_cz: "Ta rodina je chudá.", slovni_druh: "přídavné jméno" },
  { id: 373, en: "strong", cz: "silný", vyslovnost: "strong", veta_en: "The coffee is very strong.", veta_cz: "Ta káva je hodně silná.", slovni_druh: "přídavné jméno" },
  { id: 374, en: "weak", cz: "slabý", vyslovnost: "wík", veta_en: "The signal is weak.", veta_cz: "Signál je slabý.", slovni_druh: "přídavné jméno" },
  { id: 375, en: "fast", cz: "rychlý", vyslovnost: "fást", veta_en: "You drive too fast.", veta_cz: "Jedeš moc rychle.", slovni_druh: "přídavné jméno" },
  { id: 376, en: "slow", cz: "pomalý", vyslovnost: "slou", veta_en: "The internet is slow.", veta_cz: "Internet je pomalý.", slovni_druh: "přídavné jméno" },
  { id: 377, en: "heavy", cz: "těžký (váha)", vyslovnost: "hevy", veta_en: "This box is heavy.", veta_cz: "Ta krabice je těžká.", slovni_druh: "přídavné jméno" },
  { id: 378, en: "light", cz: "lehký; světlo", vyslovnost: "lajt", veta_en: "Turn on the light.", veta_cz: "Rozsviť.", slovni_druh: "přídavné jméno" },
  { id: 379, en: "dark", cz: "tmavý", vyslovnost: "dárk", veta_en: "It is dark outside.", veta_cz: "Venku je tma.", slovni_druh: "přídavné jméno" },
  { id: 380, en: "warm", cz: "teplý", vyslovnost: "wórm", veta_en: "The water is warm.", veta_cz: "Voda je teplá.", slovni_druh: "přídavné jméno" },
  { id: 381, en: "cool", cz: "chladný; super", vyslovnost: "kúl", veta_en: "The evening is cool.", veta_cz: "Večer je chladno.", slovni_druh: "přídavné jméno" },
  { id: 382, en: "dry", cz: "suchý", vyslovnost: "draj", veta_en: "The towel is dry.", veta_cz: "Ručník je suchý.", slovni_druh: "přídavné jméno" },
  { id: 383, en: "wet", cz: "mokrý", vyslovnost: "wet", veta_en: "My coat is wet.", veta_cz: "Mám mokrý kabát.", slovni_druh: "přídavné jméno" },
  { id: 384, en: "safe", cz: "bezpečný", vyslovnost: "sejf", veta_en: "This area is safe.", veta_cz: "Tahle čtvrť je bezpečná.", slovni_druh: "přídavné jméno" },
  { id: 385, en: "dangerous", cz: "nebezpečný", vyslovnost: "dejndžres", veta_en: "That road is dangerous.", veta_cz: "Ta silnice je nebezpečná.", slovni_druh: "přídavné jméno" },
  { id: 386, en: "important", cz: "důležitý", vyslovnost: "ymportnt", veta_en: "This is very important.", veta_cz: "Tohle je moc důležité.", slovni_druh: "přídavné jméno" },
  { id: 387, en: "difficult", cz: "obtížný", vyslovnost: "dyfyklt", veta_en: "The question is difficult.", veta_cz: "Ta otázka je těžká.", slovni_druh: "přídavné jméno" },
  { id: 388, en: "simple", cz: "jednoduchý", vyslovnost: "sympl", veta_en: "The answer is simple.", veta_cz: "Odpověď je jednoduchá.", slovni_druh: "přídavné jméno" },
  { id: 389, en: "possible", cz: "možný", vyslovnost: "posybl", veta_en: "Is it possible today?", veta_cz: "Je to dnes možné?", slovni_druh: "přídavné jméno" },
  { id: 390, en: "impossible", cz: "nemožný", vyslovnost: "ymposybl", veta_en: "That is impossible.", veta_cz: "To je nemožné.", slovni_druh: "přídavné jméno" },
  { id: 391, en: "ready", cz: "připravený", vyslovnost: "redy", veta_en: "I am ready to go.", veta_cz: "Jsem připravený jít.", slovni_druh: "přídavné jméno" },
  { id: 392, en: "same", cz: "stejný", vyslovnost: "sejm", veta_en: "We have the same problem.", veta_cz: "Máme stejný problém.", slovni_druh: "přídavné jméno" },
  { id: 393, en: "different", cz: "jiný, odlišný", vyslovnost: "dyfrnt", veta_en: "This is completely different.", veta_cz: "Tohle je úplně jiné.", slovni_druh: "přídavné jméno" },
  { id: 394, en: "right", cz: "správný; vpravo", vyslovnost: "rajt", veta_en: "You are right.", veta_cz: "Máš pravdu.", slovni_druh: "přídavné jméno" },
  { id: 395, en: "wrong", cz: "špatný, nesprávný", vyslovnost: "rong", veta_en: "Something is wrong.", veta_cz: "Něco je špatně.", slovni_druh: "přídavné jméno" },
  { id: 396, en: "true", cz: "pravdivý", vyslovnost: "trú", veta_en: "Is that true?", veta_cz: "Je to pravda?", slovni_druh: "přídavné jméno" },
  { id: 397, en: "false", cz: "nepravdivý, falešný", vyslovnost: "fóls", veta_en: "That is false.", veta_cz: "To není pravda.", slovni_druh: "přídavné jméno" },
  { id: 398, en: "sure", cz: "jistý", vyslovnost: "šúr", veta_en: "Are you sure?", veta_cz: "Jsi si jistý?", slovni_druh: "přídavné jméno" },
  { id: 399, en: "clear", cz: "jasný", vyslovnost: "klír", veta_en: "Is that clear?", veta_cz: "Je to jasné?", slovni_druh: "přídavné jméno" },
  { id: 400, en: "quiet", cz: "tichý", vyslovnost: "kwajet", veta_en: "The hotel is quiet.", veta_cz: "Hotel je klidný.", slovni_druh: "přídavné jméno" },
  // ---------- ÚROVEŇ 5: 401–500 (vlastnosti, fráze, jemné odstíny) ----------
  { id: 401, en: "loud", cz: "hlasitý", vyslovnost: "laud", veta_en: "The music is too loud.", veta_cz: "Hudba je moc hlasitá.", slovni_druh: "přídavné jméno" },
  { id: 402, en: "famous", cz: "slavný", vyslovnost: "fejmes", veta_en: "This place is famous.", veta_cz: "Tohle místo je slavné.", slovni_druh: "přídavné jméno" },
  { id: 403, en: "funny", cz: "vtipný", vyslovnost: "fany", veta_en: "This is funny.", veta_cz: "To je vtipné.", slovni_druh: "přídavné jméno" },
  { id: 404, en: "serious", cz: "vážný", vyslovnost: "sýries", veta_en: "Are you serious?", veta_cz: "Myslíš to vážně?", slovni_druh: "přídavné jméno" },
  { id: 405, en: "kind", cz: "laskavý; druh", vyslovnost: "kajnd", veta_en: "That is very kind of you.", veta_cz: "To je od vás moc milé.", slovni_druh: "přídavné jméno" },
  { id: 406, en: "friendly", cz: "přátelský", vyslovnost: "frendly", veta_en: "The people here are friendly.", veta_cz: "Lidi jsou tu přátelští.", slovni_druh: "přídavné jméno" },
  { id: 407, en: "polite", cz: "zdvořilý", vyslovnost: "pelajt", veta_en: "He is always polite.", veta_cz: "Vždycky je zdvořilý.", slovni_druh: "přídavné jméno" },
  { id: 408, en: "angry", cz: "naštvaný", vyslovnost: "engry", veta_en: "Do not be angry with me.", veta_cz: "Nezlob se na mě.", slovni_druh: "přídavné jméno" },
  { id: 409, en: "afraid", cz: "vystrašený, bát se", vyslovnost: "efrejd", veta_en: "I am afraid of dogs.", veta_cz: "Bojím se psů.", slovni_druh: "přídavné jméno" },
  { id: 410, en: "glad", cz: "rád", vyslovnost: "gled", veta_en: "I am glad you are here.", veta_cz: "Jsem rád, že jsi tady.", slovni_druh: "přídavné jméno" },
  { id: 411, en: "lucky", cz: "šťastný, mít štěstí", vyslovnost: "laky", veta_en: "We are lucky.", veta_cz: "Máme štěstí.", slovni_druh: "přídavné jméno" },
  { id: 412, en: "alone", cz: "sám", vyslovnost: "eloun", veta_en: "I am travelling alone.", veta_cz: "Cestuju sám.", slovni_druh: "přídavné jméno" },
  { id: 413, en: "together", cz: "spolu", vyslovnost: "tugedr", veta_en: "Let us go together.", veta_cz: "Pojďme spolu.", slovni_druh: "příslovce" },
  { id: 414, en: "everyone", cz: "všichni", vyslovnost: "evrywan", veta_en: "Everyone is here.", veta_cz: "Všichni jsou tady.", slovni_druh: "zájmeno" },
  { id: 415, en: "everything", cz: "všechno", vyslovnost: "evrysyng", veta_en: "Everything is fine.", veta_cz: "Všechno je v pořádku.", slovni_druh: "zájmeno" },
  { id: 416, en: "everywhere", cz: "všude", vyslovnost: "evrywér", veta_en: "There are tourists everywhere.", veta_cz: "Všude jsou turisti.", slovni_druh: "zájmeno" },
  { id: 417, en: "someone", cz: "někdo", vyslovnost: "samwan", veta_en: "Someone is waiting for you.", veta_cz: "Někdo na tebe čeká.", slovni_druh: "zájmeno" },
  { id: 418, en: "something", cz: "něco", vyslovnost: "samsyng", veta_en: "I want to tell you something.", veta_cz: "Chci ti něco říct.", slovni_druh: "zájmeno" },
  { id: 419, en: "somewhere", cz: "někde, někam", vyslovnost: "samwér", veta_en: "Let us go somewhere quiet.", veta_cz: "Pojďme někam do klidu.", slovni_druh: "zájmeno" },
  { id: 420, en: "nobody", cz: "nikdo", vyslovnost: "noubody", veta_en: "Nobody knows.", veta_cz: "Nikdo neví.", slovni_druh: "zájmeno" },
  { id: 421, en: "nothing", cz: "nic", vyslovnost: "nasyng", veta_en: "I have nothing.", veta_cz: "Nic nemám.", slovni_druh: "zájmeno" },
  { id: 422, en: "enough", cz: "dost", vyslovnost: "ynaf", veta_en: "That is enough, thank you.", veta_cz: "To stačí, děkuji.", slovni_druh: "příslovce" },
  { id: 423, en: "too", cz: "moc, příliš; taky", vyslovnost: "tú", veta_en: "It is too late now.", veta_cz: "Teď už je pozdě.", slovni_druh: "příslovce" },
  { id: 424, en: "last", cz: "poslední, minulý", vyslovnost: "lást", veta_en: "This is the last one.", veta_cz: "Tohle je poslední.", slovni_druh: "přídavné jméno" },
  { id: 425, en: "next", cz: "příští, další", vyslovnost: "nekst", veta_en: "The next train is at ten.", veta_cz: "Další vlak jede v deset.", slovni_druh: "přídavné jméno" },
  { id: 426, en: "near", cz: "blízko", vyslovnost: "nír", veta_en: "Is there a shop near here?", veta_cz: "Je tu někde blízko obchod?", slovni_druh: "příslovce" },
  { id: 427, en: "far", cz: "daleko", vyslovnost: "fár", veta_en: "Is it far from here?", veta_cz: "Je to odsud daleko?", slovni_druh: "příslovce" },
  { id: 428, en: "inside", cz: "uvnitř, dovnitř", vyslovnost: "ynsajd", veta_en: "Let us wait inside.", veta_cz: "Počkejme uvnitř.", slovni_druh: "příslovce" },
  { id: 429, en: "outside", cz: "venku, ven", vyslovnost: "autsajd", veta_en: "The children are outside.", veta_cz: "Děti jsou venku.", slovni_druh: "příslovce" },
  { id: 430, en: "instead", cz: "místo toho", vyslovnost: "ynsted", veta_en: "Let us take the bus instead.", veta_cz: "Pojeďme radši autobusem.", slovni_druh: "příslovce" },
  { id: 431, en: "maybe", cz: "možná", vyslovnost: "mejbí", veta_en: "Maybe tomorrow.", veta_cz: "Možná zítra.", slovni_druh: "příslovce" },
  { id: 432, en: "of course", cz: "samozřejmě", vyslovnost: "ov kórs", veta_en: "Of course, no problem.", veta_cz: "Samozřejmě, žádný problém.", slovni_druh: "fráze" },
  { id: 433, en: "really", cz: "opravdu", vyslovnost: "ryly", veta_en: "It is really good.", veta_cz: "Je to opravdu dobré.", slovni_druh: "příslovce" },
  { id: 434, en: "actually", cz: "vlastně, ve skutečnosti", vyslovnost: "ekčueli", veta_en: "Actually, I am not sure.", veta_cz: "Vlastně si nejsem jistý.", slovni_druh: "příslovce" },
  { id: 435, en: "almost", cz: "skoro", vyslovnost: "ólmoust", veta_en: "We are almost there.", veta_cz: "Už tam skoro jsme.", slovni_druh: "příslovce" },
  { id: 436, en: "probably", cz: "pravděpodobně, nejspíš", vyslovnost: "probebly", veta_en: "He is probably at home.", veta_cz: "Nejspíš je doma.", slovni_druh: "příslovce" },
  { id: 437, en: "usually", cz: "obvykle", vyslovnost: "júžueli", veta_en: "I usually get up at six.", veta_cz: "Obvykle vstávám v šest.", slovni_druh: "příslovce" },
  { id: 438, en: "finally", cz: "konečně, nakonec", vyslovnost: "fajnely", veta_en: "Finally, we are here.", veta_cz: "Konečně jsme tady.", slovni_druh: "příslovce" },
  { id: 439, en: "anyway", cz: "stejně, každopádně", vyslovnost: "enywej", veta_en: "Thank you anyway.", veta_cz: "Stejně děkuju.", slovni_druh: "příslovce" },
  { id: 440, en: "order", cz: "objednat si", vyslovnost: "órdr", veta_en: "I order a soup.", veta_cz: "Objednám si polévku.", slovni_druh: "sloveso" },
  { id: 441, en: "rest", cz: "odpočívat", vyslovnost: "rest", veta_en: "I rest after lunch.", veta_cz: "Po obědě odpočívám.", slovni_druh: "sloveso" },
  { id: 442, en: "smile", cz: "usmívat se", vyslovnost: "smajl", veta_en: "She has a nice smile.", veta_cz: "Má hezký úsměv.", slovni_druh: "sloveso" },
  { id: 443, en: "laugh", cz: "smát se", vyslovnost: "láf", veta_en: "We laugh a lot.", veta_cz: "Hodně se smějeme.", slovni_druh: "sloveso" },
  { id: 444, en: "sing", cz: "zpívat", vyslovnost: "syng", veta_en: "My wife likes to sing.", veta_cz: "Moje žena ráda zpívá.", slovni_druh: "sloveso" },
  { id: 445, en: "swim", cz: "plavat", vyslovnost: "swym", veta_en: "I swim in the sea.", veta_cz: "Plavu v moři.", slovni_druh: "sloveso" },
  { id: 446, en: "teach", cz: "učit (někoho)", vyslovnost: "tíč", veta_en: "She teaches English.", veta_cz: "Učí angličtinu.", slovni_druh: "sloveso" },
  { id: 447, en: "study", cz: "studovat, učit se", vyslovnost: "stady", veta_en: "I study English every day.", veta_cz: "Každý den se učím anglicky.", slovni_druh: "sloveso" },
  { id: 448, en: "spend", cz: "utratit, strávit", vyslovnost: "spend", veta_en: "We spend a week here.", veta_cz: "Trávíme tu týden.", slovni_druh: "sloveso" },
  { id: 449, en: "save", cz: "ušetřit, zachránit", vyslovnost: "sejv", veta_en: "I want to save money.", veta_cz: "Chci ušetřit peníze.", slovni_druh: "sloveso" },
  { id: 450, en: "rent", cz: "pronajmout si", vyslovnost: "rent", veta_en: "We rent a car.", veta_cz: "Půjčujeme si auto.", slovni_druh: "sloveso" },
  { id: 451, en: "share", cz: "sdílet, dělit se", vyslovnost: "šér", veta_en: "We share a room.", veta_cz: "Máme společný pokoj.", slovni_druh: "sloveso" },
  { id: 452, en: "hurt", cz: "bolet", vyslovnost: "hért", veta_en: "My back hurts.", veta_cz: "Bolí mě záda.", slovni_druh: "sloveso" },
  { id: 453, en: "count", cz: "počítat", vyslovnost: "kaunt", veta_en: "I count the money.", veta_cz: "Počítám peníze.", slovni_druh: "sloveso" },
  { id: 454, en: "age", cz: "věk", vyslovnost: "ejdž", veta_en: "What is your age?", veta_cz: "Kolik je vám let?", slovni_druh: "podstatné jméno" },
  { id: 455, en: "address", cz: "adresa", vyslovnost: "edres", veta_en: "This is my address.", veta_cz: "Tohle je moje adresa.", slovni_druh: "podstatné jméno" },
  { id: 456, en: "floor", cz: "podlaha, patro", vyslovnost: "flór", veta_en: "My room is on the third floor.", veta_cz: "Můj pokoj je ve třetím patře.", slovni_druh: "podstatné jméno" },
  { id: 457, en: "wall", cz: "zeď, stěna", vyslovnost: "wól", veta_en: "The picture is on the wall.", veta_cz: "Obraz je na zdi.", slovni_druh: "podstatné jméno" },
  { id: 458, en: "corner", cz: "roh", vyslovnost: "kórnr", veta_en: "The shop is on the corner.", veta_cz: "Obchod je na rohu.", slovni_druh: "podstatné jméno" },
  { id: 459, en: "towel", cz: "ručník", vyslovnost: "tauel", veta_en: "I need a clean towel.", veta_cz: "Potřebuju čistý ručník.", slovni_druh: "podstatné jméno" },
  { id: 460, en: "wallet", cz: "peněženka", vyslovnost: "wolet", veta_en: "My wallet is in my bag.", veta_cz: "Peněženka je v tašce.", slovni_druh: "podstatné jméno" },
  { id: 461, en: "cash", cz: "hotovost", vyslovnost: "keš", veta_en: "I pay in cash.", veta_cz: "Platím hotově.", slovni_druh: "podstatné jméno" },
  { id: 462, en: "bank", cz: "banka", vyslovnost: "benk", veta_en: "The bank is open now.", veta_cz: "Banka je teď otevřená.", slovni_druh: "podstatné jméno" },
  { id: 463, en: "pharmacy", cz: "lékárna", vyslovnost: "fármesy", veta_en: "Is there a pharmacy near here?", veta_cz: "Je tady blízko lékárna?", slovni_druh: "podstatné jméno" },
  { id: 464, en: "beach", cz: "pláž", vyslovnost: "bíč", veta_en: "The beach is beautiful.", veta_cz: "Pláž je krásná.", slovni_druh: "podstatné jméno" },
  { id: 465, en: "ice", cz: "led", vyslovnost: "ajs", veta_en: "Water with ice, please.", veta_cz: "Vodu s ledem, prosím.", slovni_druh: "podstatné jméno" },
  { id: 466, en: "butter", cz: "máslo", vyslovnost: "batr", veta_en: "Bread with butter.", veta_cz: "Chleba s máslem.", slovni_druh: "podstatné jméno" },
  { id: 467, en: "pain", cz: "bolest", vyslovnost: "pejn", veta_en: "I have a pain here.", veta_cz: "Bolí mě tady.", slovni_druh: "podstatné jméno" },
  { id: 468, en: "tall", cz: "vysoký (o člověku)", vyslovnost: "tól", veta_en: "My son is tall.", veta_cz: "Můj syn je vysoký.", slovni_druh: "přídavné jméno" },
  { id: 469, en: "thin", cz: "hubený, tenký", vyslovnost: "syn", veta_en: "The soup is too thin.", veta_cz: "Ta polévka je moc řídká.", slovni_druh: "přídavné jméno" },
  { id: 470, en: "sweet", cz: "sladký", vyslovnost: "swít", veta_en: "The wine is very sweet.", veta_cz: "To víno je moc sladké.", slovni_druh: "přídavné jméno" },
  { id: 471, en: "soft", cz: "měkký", vyslovnost: "soft", veta_en: "The bed is soft.", veta_cz: "Postel je měkká.", slovni_druh: "přídavné jméno" },
  { id: 472, en: "sick", cz: "nemocný", vyslovnost: "syk", veta_en: "I feel sick.", veta_cz: "Je mi špatně.", slovni_druh: "přídavné jméno" },
  { id: 473, en: "healthy", cz: "zdravý", vyslovnost: "helsy", veta_en: "He is old but healthy.", veta_cz: "Je starý, ale zdravý.", slovni_druh: "přídavné jméno" },
  { id: 474, en: "fresh", cz: "čerstvý", vyslovnost: "freš", veta_en: "The fish is fresh.", veta_cz: "Ta ryba je čerstvá.", slovni_druh: "přídavné jméno" },
  { id: 475, en: "careful", cz: "opatrný", vyslovnost: "kérful", veta_en: "Be careful, the road is wet.", veta_cz: "Buď opatrný, silnice je mokrá.", slovni_druh: "přídavné jméno" },
  { id: 476, en: "excuse me", cz: "promiňte, s dovolením", vyslovnost: "yksk-jůz mí", veta_en: "Excuse me, where is the station?", veta_cz: "Promiňte, kde je nádraží?", slovni_druh: "fráze" },
  { id: 477, en: "I don't understand", cz: "nerozumím", vyslovnost: "aj dount andr-stend", veta_en: "I am sorry, I don't understand.", veta_cz: "Promiňte, nerozumím.", slovni_druh: "fráze" },
  { id: 478, en: "can you help me?", cz: "můžete mi pomoct?", vyslovnost: "ken jů help mí", veta_en: "Can you help me, please?", veta_cz: "Můžete mi prosím pomoct?", slovni_druh: "fráze" },
  { id: 479, en: "how much is it?", cz: "kolik to stojí?", vyslovnost: "hau mač yz yt", veta_en: "How much is it, please?", veta_cz: "Kolik to prosím stojí?", slovni_druh: "fráze" },
  { id: 480, en: "I would like", cz: "dal bych si, chtěl bych", vyslovnost: "aj wud lajk", veta_en: "I would like a coffee, please.", veta_cz: "Dal bych si kávu, prosím.", slovni_druh: "fráze" },
  { id: 481, en: "where is the toilet?", cz: "kde je záchod?", vyslovnost: "wér yz de tojlet", veta_en: "Excuse me, where is the toilet?", veta_cz: "Promiňte, kde je záchod?", slovni_druh: "fráze" },
  { id: 482, en: "see you later", cz: "uvidíme se později", vyslovnost: "sí jů lejtr", veta_en: "Thank you, see you later.", veta_cz: "Děkuji, uvidíme se později.", slovni_druh: "fráze" },
  { id: 483, en: "nice to meet you", cz: "těší mě", vyslovnost: "najs tu mít jů", veta_en: "Hello, nice to meet you.", veta_cz: "Dobrý den, těší mě.", slovni_druh: "fráze" },
  { id: 484, en: "no problem", cz: "žádný problém", vyslovnost: "nou problem", veta_en: "No problem, take your time.", veta_cz: "Žádný problém, jen klid.", slovni_druh: "fráze" },
  { id: 485, en: "you are welcome", cz: "není zač", vyslovnost: "jů ár welkm", veta_en: "Thank you! You are welcome.", veta_cz: "Děkuji! Není zač.", slovni_druh: "fráze" },
  { id: 486, en: "please speak slowly", cz: "mluvte prosím pomalu", vyslovnost: "plíz spík slouli", veta_en: "Please speak slowly, I am learning.", veta_cz: "Mluvte prosím pomalu, učím se.", slovni_druh: "fráze" },
  { id: 487, en: "I don't know", cz: "nevím", vyslovnost: "aj dount nou", veta_en: "I am sorry, I don't know.", veta_cz: "Promiňte, nevím.", slovni_druh: "fráze" },
  { id: 488, en: "how are you?", cz: "jak se máš?", vyslovnost: "hau ár jů", veta_en: "Hello, how are you?", veta_cz: "Ahoj, jak se máš?", slovni_druh: "fráze" },
  { id: 489, en: "what time is it?", cz: "kolik je hodin?", vyslovnost: "wot tajm yz yt", veta_en: "Excuse me, what time is it?", veta_cz: "Promiňte, kolik je hodin?", slovni_druh: "fráze" },
  { id: 490, en: "good morning", cz: "dobré ráno", vyslovnost: "gud mórnyng", veta_en: "Good morning, a coffee please.", veta_cz: "Dobré ráno, kávu prosím.", slovni_druh: "fráze" },
  { id: 491, en: "good night", cz: "dobrou noc", vyslovnost: "gud najt", veta_en: "Good night, sleep well.", veta_cz: "Dobrou noc, dobře se vyspi.", slovni_druh: "fráze" },
  { id: 492, en: "can you repeat that?", cz: "můžete to zopakovat?", vyslovnost: "ken jů rypít det", veta_en: "Can you repeat that, please?", veta_cz: "Můžete to prosím zopakovat?", slovni_druh: "fráze" },
  { id: 493, en: "the bill, please", cz: "účet, prosím", vyslovnost: "de byl plíz", veta_en: "The bill, please. We are ready.", veta_cz: "Účet, prosím. Jsme připravení.", slovni_druh: "fráze" },
  { id: 494, en: "I need a doctor", cz: "potřebuju doktora", vyslovnost: "aj níd e doktr", veta_en: "Help, I need a doctor.", veta_cz: "Pomoc, potřebuju doktora.", slovni_druh: "fráze" },
  { id: 495, en: "how do you say...?", cz: "jak se řekne...?", vyslovnost: "hau dů jů sej", veta_en: "How do you say this in English?", veta_cz: "Jak se tohle řekne anglicky?", slovni_druh: "fráze" },
  { id: 496, en: "I am lost", cz: "ztratil jsem se", vyslovnost: "aj em lost", veta_en: "Excuse me, I am lost.", veta_cz: "Promiňte, ztratil jsem se.", slovni_druh: "fráze" },
  { id: 497, en: "just a moment", cz: "moment, chvilku", vyslovnost: "džast e moument", veta_en: "Just a moment, please.", veta_cz: "Chvilku, prosím.", slovni_druh: "fráze" },
  { id: 498, en: "have a nice day", cz: "hezký den", vyslovnost: "hev e najs dej", veta_en: "Goodbye, have a nice day!", veta_cz: "Na shledanou, hezký den!", slovni_druh: "fráze" },
  { id: 499, en: "I am looking for", cz: "hledám", vyslovnost: "aj em lukyng fór", veta_en: "I am looking for the station.", veta_cz: "Hledám nádraží.", slovni_druh: "fráze" },
  { id: 500, en: "that is all", cz: "to je všechno", vyslovnost: "det yz ól", veta_en: "That is all, thank you.", veta_cz: "To je všechno, děkuji.", slovni_druh: "fráze" },
];
