// 100 nejpoužívanějších ŠPANĚLSKÝCH slov pro tátu.
// Editace: přidej/uprav záznam v tomto poli a ulož. Nic víc není potřeba.
// Pole:
//   id            – jednoznačné číslo (neopakuj)
//   es            – španělsky (u podstatných jmen bez členu; člen je v poli "clen")
//   cz            – česky
//   vyslovnost    – český fonetický přepis; jen tam, kde by to šlo přečíst špatně (jinak "")
//   veta_es       – krátká použitelná věta španělsky
//   veta_cz       – její český překlad
//   en            – anglicky (nápověda pro anglicky mluvící, kteří se učí španělsky)
//   veta_en       – anglický překlad věty veta_es
//   vyslovnost_en – výslovnost španělštiny „po anglicku“ (slabiky, VELKÝMI = přízvuk)
//   slovni_druh   – "sloveso" | "podstatné jméno" | "přídavné jméno" | "funkční slovo"
//   clen          – "el" / "la" u podstatných jmen, jinak ""
window.SLOVA_ES = [
  // ---------- SLOVESA (30) ----------
  { id: 1, es: "ser", cz: "být (trvale)", vyslovnost: "", veta_es: "Yo soy de la República Checa.", veta_cz: "Jsem z České republiky.", en: "to be (permanent)", veta_en: "I am from the Czech Republic.", vyslovnost_en: "sehr", slovni_druh: "sloveso", clen: "" },
  { id: 2, es: "estar", cz: "být (stav, poloha)", vyslovnost: "", veta_es: "¿Dónde estás ahora?", veta_cz: "Kde teď jsi?", en: "to be (state, location)", veta_en: "Where are you now?", vyslovnost_en: "ehs-TAHR", slovni_druh: "sloveso", clen: "" },
  { id: 3, es: "tener", cz: "mít", vyslovnost: "", veta_es: "Tengo dos hijos.", veta_cz: "Mám dvě děti.", en: "to have", veta_en: "I have two children.", vyslovnost_en: "teh-NEHR", slovni_druh: "sloveso", clen: "" },
  { id: 4, es: "hacer", cz: "dělat", vyslovnost: "asér", veta_es: "¿Qué haces hoy?", veta_cz: "Co dnes děláš?", en: "to do, to make", veta_en: "What are you doing today?", vyslovnost_en: "ah-SEHR", slovni_druh: "sloveso", clen: "" },
  { id: 5, es: "ir", cz: "jít, jet", vyslovnost: "", veta_es: "Voy a la playa.", veta_cz: "Jdu na pláž.", en: "to go", veta_en: "I'm going to the beach.", vyslovnost_en: "eer", slovni_druh: "sloveso", clen: "" },
  { id: 6, es: "poder", cz: "moci", vyslovnost: "", veta_es: "¿Puedes ayudarme?", veta_cz: "Můžeš mi pomoct?", en: "can, to be able to", veta_en: "Can you help me?", vyslovnost_en: "poh-DEHR", slovni_druh: "sloveso", clen: "" },
  { id: 7, es: "querer", cz: "chtít, mít rád", vyslovnost: "kerér", veta_es: "Quiero un café, por favor.", veta_cz: "Chci kávu, prosím.", en: "to want; to love", veta_en: "I want a coffee, please.", vyslovnost_en: "keh-REHR", slovni_druh: "sloveso", clen: "" },
  { id: 8, es: "saber", cz: "vědět, umět", vyslovnost: "", veta_es: "No sé dónde está.", veta_cz: "Nevím, kde to je.", en: "to know, to know how to", veta_en: "I don't know where it is.", vyslovnost_en: "sah-BEHR", slovni_druh: "sloveso", clen: "" },
  { id: 9, es: "ver", cz: "vidět", vyslovnost: "", veta_es: "Quiero ver el mar.", veta_cz: "Chci vidět moře.", en: "to see", veta_en: "I want to see the sea.", vyslovnost_en: "behr", slovni_druh: "sloveso", clen: "" },
  { id: 10, es: "dar", cz: "dát", vyslovnost: "", veta_es: "¿Me das agua?", veta_cz: "Dáš mi vodu?", en: "to give", veta_en: "Will you give me some water?", vyslovnost_en: "dahr", slovni_druh: "sloveso", clen: "" },
  { id: 11, es: "hablar", cz: "mluvit", vyslovnost: "ablár", veta_es: "No hablo mucho español.", veta_cz: "Nemluvím moc španělsky.", en: "to speak", veta_en: "I don't speak much Spanish.", vyslovnost_en: "ah-BLAHR", slovni_druh: "sloveso", clen: "" },
  { id: 12, es: "comer", cz: "jíst", vyslovnost: "", veta_es: "Vamos a comer algo.", veta_cz: "Pojďme si něco sníst.", en: "to eat", veta_en: "Let's eat something.", vyslovnost_en: "koh-MEHR", slovni_druh: "sloveso", clen: "" },
  { id: 13, es: "beber", cz: "pít", vyslovnost: "", veta_es: "¿Quieres beber algo?", veta_cz: "Chceš se něčeho napít?", en: "to drink", veta_en: "Do you want something to drink?", vyslovnost_en: "beh-BEHR", slovni_druh: "sloveso", clen: "" },
  { id: 14, es: "vivir", cz: "žít, bydlet", vyslovnost: "", veta_es: "Vivo en Praga.", veta_cz: "Bydlím v Praze.", en: "to live", veta_en: "I live in Prague.", vyslovnost_en: "bee-BEER", slovni_druh: "sloveso", clen: "" },
  { id: 15, es: "venir", cz: "přijít", vyslovnost: "", veta_es: "¿Vienes conmigo?", veta_cz: "Jdeš se mnou?", en: "to come", veta_en: "Are you coming with me?", vyslovnost_en: "beh-NEER", slovni_druh: "sloveso", clen: "" },
  { id: 16, es: "decir", cz: "říct", vyslovnost: "decír", veta_es: "¿Qué quieres decir?", veta_cz: "Co tím chceš říct?", en: "to say, to tell", veta_en: "What do you mean?", vyslovnost_en: "deh-SEER", slovni_druh: "sloveso", clen: "" },
  { id: 17, es: "poner", cz: "položit, dát", vyslovnost: "", veta_es: "Pon la bolsa aquí.", veta_cz: "Polož tašku sem.", en: "to put, to place", veta_en: "Put the bag here.", vyslovnost_en: "poh-NEHR", slovni_druh: "sloveso", clen: "" },
  { id: 18, es: "salir", cz: "vyjít, odejít", vyslovnost: "", veta_es: "Salgo de casa a las ocho.", veta_cz: "Odcházím z domu v osm.", en: "to go out, to leave", veta_en: "I leave home at eight.", vyslovnost_en: "sah-LEER", slovni_druh: "sloveso", clen: "" },
  { id: 19, es: "llegar", cz: "dorazit, přijet", vyslovnost: "jegár", veta_es: "El tren llega tarde.", veta_cz: "Vlak přijíždí pozdě.", en: "to arrive", veta_en: "The train arrives late.", vyslovnost_en: "yeh-GAHR", slovni_druh: "sloveso", clen: "" },
  { id: 20, es: "pasar", cz: "stát se, projít", vyslovnost: "", veta_es: "¿Qué pasa?", veta_cz: "Co se děje?", en: "to happen; to pass", veta_en: "What's happening?", vyslovnost_en: "pah-SAHR", slovni_druh: "sloveso", clen: "" },
  { id: 21, es: "deber", cz: "muset, mít povinnost", vyslovnost: "", veta_es: "Debo trabajar mañana.", veta_cz: "Musím zítra pracovat.", en: "must, to have to", veta_en: "I must work tomorrow.", vyslovnost_en: "deh-BEHR", slovni_druh: "sloveso", clen: "" },
  { id: 22, es: "necesitar", cz: "potřebovat", vyslovnost: "necesitár", veta_es: "Necesito ayuda.", veta_cz: "Potřebuju pomoc.", en: "to need", veta_en: "I need help.", vyslovnost_en: "neh-seh-see-TAHR", slovni_druh: "sloveso", clen: "" },
  { id: 23, es: "gustar", cz: "líbit se, chutnat", vyslovnost: "", veta_es: "Me gusta el café.", veta_cz: "Mám rád kávu.", en: "to like (to be pleasing)", veta_en: "I like coffee.", vyslovnost_en: "goos-TAHR", slovni_druh: "sloveso", clen: "" },
  { id: 24, es: "comprar", cz: "koupit", vyslovnost: "", veta_es: "Quiero comprar pan.", veta_cz: "Chci koupit chleba.", en: "to buy", veta_en: "I want to buy bread.", vyslovnost_en: "kohm-PRAHR", slovni_druh: "sloveso", clen: "" },
  { id: 25, es: "trabajar", cz: "pracovat", vyslovnost: "trabachár", veta_es: "Trabajo en una tienda.", veta_cz: "Pracuju v obchodě.", en: "to work", veta_en: "I work in a shop.", vyslovnost_en: "trah-bah-HAHR", slovni_druh: "sloveso", clen: "" },
  { id: 26, es: "entender", cz: "rozumět", vyslovnost: "", veta_es: "No entiendo bien.", veta_cz: "Moc nerozumím.", en: "to understand", veta_en: "I don't understand well.", vyslovnost_en: "ehn-tehn-DEHR", slovni_druh: "sloveso", clen: "" },
  { id: 27, es: "ayudar", cz: "pomáhat", vyslovnost: "ajudár", veta_es: "¿Puede ayudarme, por favor?", veta_cz: "Můžete mi prosím pomoct?", en: "to help", veta_en: "Could you help me, please?", vyslovnost_en: "ah-yoo-DAHR", slovni_druh: "sloveso", clen: "" },
  { id: 28, es: "buscar", cz: "hledat", vyslovnost: "", veta_es: "Busco un hotel.", veta_cz: "Hledám hotel.", en: "to look for", veta_en: "I'm looking for a hotel.", vyslovnost_en: "boos-KAHR", slovni_druh: "sloveso", clen: "" },
  { id: 29, es: "encontrar", cz: "najít", vyslovnost: "", veta_es: "No encuentro la llave.", veta_cz: "Nemůžu najít klíč.", en: "to find", veta_en: "I can't find the key.", vyslovnost_en: "ehn-kohn-TRAHR", slovni_druh: "sloveso", clen: "" },
  { id: 30, es: "pensar", cz: "myslet", vyslovnost: "", veta_es: "Pienso que sí.", veta_cz: "Myslím, že ano.", en: "to think", veta_en: "I think so.", vyslovnost_en: "pehn-SAHR", slovni_druh: "sloveso", clen: "" },

  // ---------- PODSTATNÁ JMÉNA (40) ----------
  { id: 31, es: "día", cz: "den", vyslovnost: "", veta_es: "Buenos días, señor.", veta_cz: "Dobrý den, pane.", en: "day", veta_en: "Good morning, sir.", vyslovnost_en: "DEE-ah", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 32, es: "casa", cz: "dům, domov", vyslovnost: "", veta_es: "Estoy en casa.", veta_cz: "Jsem doma.", en: "house, home", veta_en: "I'm at home.", vyslovnost_en: "KAH-sah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 33, es: "agua", cz: "voda", vyslovnost: "", veta_es: "Quiero un vaso de agua.", veta_cz: "Chci sklenici vody.", en: "water", veta_en: "I want a glass of water.", vyslovnost_en: "AH-gwah", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 34, es: "tiempo", cz: "čas, počasí", vyslovnost: "", veta_es: "No tengo tiempo.", veta_cz: "Nemám čas.", en: "time; weather", veta_en: "I don't have time.", vyslovnost_en: "TYEHM-poh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 35, es: "año", cz: "rok", vyslovnost: "aňo", veta_es: "Tengo sesenta años.", veta_cz: "Je mi šedesát let.", en: "year", veta_en: "I'm sixty years old.", vyslovnost_en: "AH-nyoh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 36, es: "hombre", cz: "muž, člověk", vyslovnost: "ombre", veta_es: "Ese hombre es mi amigo.", veta_cz: "Ten muž je můj přítel.", en: "man", veta_en: "That man is my friend.", vyslovnost_en: "OHM-breh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 37, es: "mujer", cz: "žena", vyslovnost: "mucher", veta_es: "La mujer trabaja aquí.", veta_cz: "Ta žena tady pracuje.", en: "woman", veta_en: "The woman works here.", vyslovnost_en: "moo-HEHR", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 38, es: "niño", cz: "dítě, kluk", vyslovnost: "niňo", veta_es: "El niño juega en la calle.", veta_cz: "Dítě si hraje na ulici.", en: "child, boy", veta_en: "The child plays in the street.", vyslovnost_en: "NEE-nyoh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 39, es: "amigo", cz: "přítel, kamarád", vyslovnost: "", veta_es: "Es un buen amigo.", veta_cz: "Je to dobrý kamarád.", en: "friend", veta_en: "He's a good friend.", vyslovnost_en: "ah-MEE-goh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 40, es: "comida", cz: "jídlo", vyslovnost: "", veta_es: "La comida está muy buena.", veta_cz: "Jídlo je moc dobré.", en: "food, meal", veta_en: "The food is very good.", vyslovnost_en: "koh-MEE-dah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 41, es: "noche", cz: "noc", vyslovnost: "noče", veta_es: "Buenas noches.", veta_cz: "Dobrou noc.", en: "night", veta_en: "Good night.", vyslovnost_en: "NOH-cheh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 42, es: "mañana", cz: "ráno, zítra", vyslovnost: "maňana", veta_es: "Hasta mañana.", veta_cz: "Zítra na shledanou.", en: "morning; tomorrow", veta_en: "See you tomorrow.", vyslovnost_en: "mah-NYAH-nah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 43, es: "gente", cz: "lidé", vyslovnost: "chente", veta_es: "Hay mucha gente aquí.", veta_cz: "Je tu hodně lidí.", en: "people", veta_en: "There are a lot of people here.", vyslovnost_en: "HEHN-teh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 44, es: "cosa", cz: "věc", vyslovnost: "", veta_es: "Es una cosa importante.", veta_cz: "Je to důležitá věc.", en: "thing", veta_en: "It's an important thing.", vyslovnost_en: "KOH-sah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 45, es: "vida", cz: "život", vyslovnost: "", veta_es: "Así es la vida.", veta_cz: "Takový je život.", en: "life", veta_en: "That's life.", vyslovnost_en: "BEE-dah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 46, es: "trabajo", cz: "práce", vyslovnost: "trabacho", veta_es: "Me gusta mi trabajo.", veta_cz: "Mám rád svou práci.", en: "work, job", veta_en: "I like my job.", vyslovnost_en: "trah-BAH-hoh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 47, es: "ciudad", cz: "město", vyslovnost: "siudad", veta_es: "Madrid es una ciudad grande.", veta_cz: "Madrid je velké město.", en: "city", veta_en: "Madrid is a big city.", vyslovnost_en: "syoo-DAHD", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 48, es: "país", cz: "země, stát", vyslovnost: "pa-ís", veta_es: "España es un país bonito.", veta_cz: "Španělsko je krásná země.", en: "country", veta_en: "Spain is a beautiful country.", vyslovnost_en: "pah-EES", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 49, es: "mundo", cz: "svět", vyslovnost: "", veta_es: "Quiero ver el mundo.", veta_cz: "Chci vidět svět.", en: "world", veta_en: "I want to see the world.", vyslovnost_en: "MOON-doh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 50, es: "coche", cz: "auto", vyslovnost: "koče", veta_es: "El coche es nuevo.", veta_cz: "To auto je nové.", en: "car", veta_en: "The car is new.", vyslovnost_en: "KOH-cheh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 51, es: "calle", cz: "ulice", vyslovnost: "kaje", veta_es: "Vivo en esta calle.", veta_cz: "Bydlím v této ulici.", en: "street", veta_en: "I live on this street.", vyslovnost_en: "KAH-yeh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 52, es: "dinero", cz: "peníze", vyslovnost: "", veta_es: "No tengo dinero.", veta_cz: "Nemám peníze.", en: "money", veta_en: "I don't have any money.", vyslovnost_en: "dee-NEH-roh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 53, es: "hora", cz: "hodina", vyslovnost: "ora", veta_es: "¿Qué hora es?", veta_cz: "Kolik je hodin?", en: "hour; time", veta_en: "What time is it?", vyslovnost_en: "OH-rah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 54, es: "semana", cz: "týden", vyslovnost: "", veta_es: "Nos vemos la próxima semana.", veta_cz: "Uvidíme se příští týden.", en: "week", veta_en: "See you next week.", vyslovnost_en: "seh-MAH-nah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 55, es: "mes", cz: "měsíc", vyslovnost: "", veta_es: "Voy a España este mes.", veta_cz: "Tento měsíc jedu do Španělska.", en: "month", veta_en: "I'm going to Spain this month.", vyslovnost_en: "mehs", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 56, es: "nombre", cz: "jméno", vyslovnost: "", veta_es: "¿Cuál es tu nombre?", veta_cz: "Jak se jmenuješ?", en: "name", veta_en: "What's your name?", vyslovnost_en: "NOHM-breh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 57, es: "familia", cz: "rodina", vyslovnost: "", veta_es: "Mi familia vive aquí.", veta_cz: "Moje rodina žije tady.", en: "family", veta_en: "My family lives here.", vyslovnost_en: "fah-MEE-lyah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 58, es: "padre", cz: "otec, táta", vyslovnost: "", veta_es: "Mi padre es alto.", veta_cz: "Můj táta je vysoký.", en: "father, dad", veta_en: "My father is tall.", vyslovnost_en: "PAH-dreh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 59, es: "madre", cz: "matka, máma", vyslovnost: "", veta_es: "Mi madre cocina bien.", veta_cz: "Moje máma dobře vaří.", en: "mother, mom", veta_en: "My mother cooks well.", vyslovnost_en: "MAH-dreh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 60, es: "hijo", cz: "syn", vyslovnost: "icho", veta_es: "Su hijo tiene diez años.", veta_cz: "Jeho syn má deset let.", en: "son", veta_en: "His son is ten years old.", vyslovnost_en: "EE-hoh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 61, es: "mano", cz: "ruka", vyslovnost: "", veta_es: "Dame la mano.", veta_cz: "Podej mi ruku.", en: "hand", veta_en: "Give me your hand.", vyslovnost_en: "MAH-noh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 62, es: "puerta", cz: "dveře", vyslovnost: "puerta", veta_es: "Cierra la puerta, por favor.", veta_cz: "Zavři dveře, prosím.", en: "door", veta_en: "Close the door, please.", vyslovnost_en: "PWEHR-tah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 63, es: "mesa", cz: "stůl", vyslovnost: "", veta_es: "Una mesa para dos, por favor.", veta_cz: "Stůl pro dva, prosím.", en: "table", veta_en: "A table for two, please.", vyslovnost_en: "MEH-sah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 64, es: "pan", cz: "chleba", vyslovnost: "", veta_es: "Quiero pan con tomate.", veta_cz: "Chci chleba s rajčaty.", en: "bread", veta_en: "I want bread with tomato.", vyslovnost_en: "pahn", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 65, es: "café", cz: "káva", vyslovnost: "", veta_es: "Un café con leche, por favor.", veta_cz: "Kávu s mlékem, prosím.", en: "coffee", veta_en: "A coffee with milk, please.", vyslovnost_en: "kah-FEH", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 66, es: "leche", cz: "mléko", vyslovnost: "leče", veta_es: "No tomo leche.", veta_cz: "Nepiju mléko.", en: "milk", veta_en: "I don't drink milk.", vyslovnost_en: "LEH-cheh", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 67, es: "baño", cz: "koupelna, záchod", vyslovnost: "baňo", veta_es: "¿Dónde está el baño?", veta_cz: "Kde je záchod?", en: "bathroom, toilet", veta_en: "Where is the bathroom?", vyslovnost_en: "BAH-nyoh", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 68, es: "playa", cz: "pláž", vyslovnost: "plaja", veta_es: "La playa está cerca.", veta_cz: "Pláž je blízko.", en: "beach", veta_en: "The beach is nearby.", vyslovnost_en: "PLAH-yah", slovni_druh: "podstatné jméno", clen: "la" },
  { id: 69, es: "sol", cz: "slunce", vyslovnost: "", veta_es: "Hoy hace sol.", veta_cz: "Dnes svítí slunce.", en: "sun", veta_en: "It's sunny today.", vyslovnost_en: "sohl", slovni_druh: "podstatné jméno", clen: "el" },
  { id: 70, es: "tienda", cz: "obchod", vyslovnost: "", veta_es: "La tienda está cerrada.", veta_cz: "Obchod je zavřený.", en: "shop, store", veta_en: "The shop is closed.", vyslovnost_en: "TYEHN-dah", slovni_druh: "podstatné jméno", clen: "la" },

  // ---------- PŘÍDAVNÁ JMÉNA (15) ----------
  { id: 71, es: "bueno", cz: "dobrý", vyslovnost: "bueno", veta_es: "Es un vino muy bueno.", veta_cz: "To je moc dobré víno.", en: "good", veta_en: "It's a very good wine.", vyslovnost_en: "BWEH-noh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 72, es: "malo", cz: "špatný", vyslovnost: "", veta_es: "Hoy hace mal tiempo.", veta_cz: "Dnes je špatné počasí.", en: "bad", veta_en: "The weather is bad today.", vyslovnost_en: "MAH-loh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 73, es: "grande", cz: "velký", vyslovnost: "grande", veta_es: "Es una casa grande.", veta_cz: "Je to velký dům.", en: "big, large", veta_en: "It's a big house.", vyslovnost_en: "GRAHN-deh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 74, es: "pequeño", cz: "malý", vyslovnost: "pekeňo", veta_es: "Quiero un café pequeño.", veta_cz: "Chci malou kávu.", en: "small, little", veta_en: "I want a small coffee.", vyslovnost_en: "peh-KEH-nyoh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 75, es: "nuevo", cz: "nový", vyslovnost: "nuevo", veta_es: "Tengo un coche nuevo.", veta_cz: "Mám nové auto.", en: "new", veta_en: "I have a new car.", vyslovnost_en: "NWEH-boh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 76, es: "viejo", cz: "starý", vyslovnost: "viecho", veta_es: "Es un pueblo muy viejo.", veta_cz: "Je to hodně staré městečko.", en: "old", veta_en: "It's a very old town.", vyslovnost_en: "BYEH-hoh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 77, es: "mucho", cz: "hodně, mnoho", vyslovnost: "mučo", veta_es: "Muchas gracias.", veta_cz: "Mnohokrát děkuji.", en: "a lot, much", veta_en: "Thank you very much.", vyslovnost_en: "MOO-choh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 78, es: "poco", cz: "málo", vyslovnost: "", veta_es: "Hablo un poco de español.", veta_cz: "Mluvím trochu španělsky.", en: "little, few", veta_en: "I speak a little Spanish.", vyslovnost_en: "POH-koh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 79, es: "bonito", cz: "hezký, pěkný", vyslovnost: "", veta_es: "¡Qué bonito!", veta_cz: "To je hezké!", en: "nice, pretty", veta_en: "How nice!", vyslovnost_en: "boh-NEE-toh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 80, es: "feo", cz: "ošklivý", vyslovnost: "", veta_es: "El tiempo está feo hoy.", veta_cz: "Počasí je dnes ošklivé.", en: "ugly", veta_en: "The weather is nasty today.", vyslovnost_en: "FEH-oh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 81, es: "fácil", cz: "snadný", vyslovnost: "fásil", veta_es: "El español es fácil.", veta_cz: "Španělština je snadná.", en: "easy", veta_en: "Spanish is easy.", vyslovnost_en: "FAH-seel", slovni_druh: "přídavné jméno", clen: "" },
  { id: 82, es: "difícil", cz: "těžký, obtížný", vyslovnost: "difísil", veta_es: "Es difícil para mí.", veta_cz: "Je to pro mě těžké.", en: "hard, difficult", veta_en: "It's hard for me.", vyslovnost_en: "dee-FEE-seel", slovni_druh: "přídavné jméno", clen: "" },
  { id: 83, es: "caro", cz: "drahý", vyslovnost: "", veta_es: "Este hotel es muy caro.", veta_cz: "Tento hotel je moc drahý.", en: "expensive", veta_en: "This hotel is very expensive.", vyslovnost_en: "KAH-roh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 84, es: "barato", cz: "levný", vyslovnost: "", veta_es: "El menú es barato.", veta_cz: "To menu je levné.", en: "cheap", veta_en: "The set menu is cheap.", vyslovnost_en: "bah-RAH-toh", slovni_druh: "přídavné jméno", clen: "" },
  { id: 85, es: "feliz", cz: "šťastný", vyslovnost: "felís", veta_es: "Estoy muy feliz hoy.", veta_cz: "Dnes jsem moc šťastný.", en: "happy", veta_en: "I'm very happy today.", vyslovnost_en: "feh-LEES", slovni_druh: "přídavné jméno", clen: "" },

  // ---------- FUNKČNÍ SLOVA A FRÁZE (15) ----------
  { id: 86, es: "dónde", cz: "kde", vyslovnost: "donde", veta_es: "¿Dónde está la estación?", veta_cz: "Kde je nádraží?", en: "where", veta_en: "Where is the station?", vyslovnost_en: "DOHN-deh", slovni_druh: "funkční slovo", clen: "" },
  { id: 87, es: "cuándo", cz: "kdy", vyslovnost: "kuando", veta_es: "¿Cuándo llega el autobús?", veta_cz: "Kdy přijede autobus?", en: "when", veta_en: "When does the bus arrive?", vyslovnost_en: "KWAHN-doh", slovni_druh: "funkční slovo", clen: "" },
  { id: 88, es: "cómo", cz: "jak", vyslovnost: "komo", veta_es: "¿Cómo estás?", veta_cz: "Jak se máš?", en: "how", veta_en: "How are you?", vyslovnost_en: "KOH-moh", slovni_druh: "funkční slovo", clen: "" },
  { id: 89, es: "qué", cz: "co, jaký", vyslovnost: "ke", veta_es: "¿Qué es esto?", veta_cz: "Co je to?", en: "what", veta_en: "What is this?", vyslovnost_en: "keh", slovni_druh: "funkční slovo", clen: "" },
  { id: 90, es: "por qué", cz: "proč", vyslovnost: "por ke", veta_es: "¿Por qué no vienes?", veta_cz: "Proč nejdeš?", en: "why", veta_en: "Why don't you come?", vyslovnost_en: "pohr KEH", slovni_druh: "funkční slovo", clen: "" },
  { id: 91, es: "porque", cz: "protože", vyslovnost: "porke", veta_es: "No voy porque estoy cansado.", veta_cz: "Nejdu, protože jsem unavený.", en: "because", veta_en: "I'm not going because I'm tired.", vyslovnost_en: "POHR-keh", slovni_druh: "funkční slovo", clen: "" },
  { id: 92, es: "también", cz: "také", vyslovnost: "tambien", veta_es: "Yo también quiero ir.", veta_cz: "Já chci jet taky.", en: "also, too", veta_en: "I want to go too.", vyslovnost_en: "tahm-BYEHN", slovni_druh: "funkční slovo", clen: "" },
  { id: 93, es: "pero", cz: "ale", vyslovnost: "", veta_es: "Quiero ir, pero no puedo.", veta_cz: "Chci jít, ale nemůžu.", en: "but", veta_en: "I want to go, but I can't.", vyslovnost_en: "PEH-roh", slovni_druh: "funkční slovo", clen: "" },
  { id: 94, es: "muy", cz: "velmi, moc", vyslovnost: "muj", veta_es: "Es muy tarde.", veta_cz: "Je moc pozdě.", en: "very", veta_en: "It's very late.", vyslovnost_en: "mwee", slovni_druh: "funkční slovo", clen: "" },
  { id: 95, es: "ahora", cz: "teď", vyslovnost: "aora", veta_es: "Tengo que irme ahora.", veta_cz: "Musím teď jít.", en: "now", veta_en: "I have to go now.", vyslovnost_en: "ah-OH-rah", slovni_druh: "funkční slovo", clen: "" },
  { id: 96, es: "aquí", cz: "tady", vyslovnost: "akí", veta_es: "Espera aquí, por favor.", veta_cz: "Počkej tady, prosím.", en: "here", veta_en: "Wait here, please.", vyslovnost_en: "ah-KEE", slovni_druh: "funkční slovo", clen: "" },
  { id: 97, es: "allí", cz: "tam", vyslovnost: "ají", veta_es: "El hotel está allí.", veta_cz: "Hotel je tamhle.", en: "there", veta_en: "The hotel is over there.", vyslovnost_en: "ah-YEE", slovni_druh: "funkční slovo", clen: "" },
  { id: 98, es: "siempre", cz: "vždy", vyslovnost: "siempre", veta_es: "Siempre tomo café.", veta_cz: "Vždycky si dám kávu.", en: "always", veta_en: "I always have coffee.", vyslovnost_en: "SYEHM-preh", slovni_druh: "funkční slovo", clen: "" },
  { id: 99, es: "nunca", cz: "nikdy", vyslovnost: "nunka", veta_es: "Nunca voy a la playa.", veta_cz: "Nikdy nechodím na pláž.", en: "never", veta_en: "I never go to the beach.", vyslovnost_en: "NOON-kah", slovni_druh: "funkční slovo", clen: "" },
  { id: 100, es: "gracias", cz: "děkuji", vyslovnost: "grasias", veta_es: "Gracias por todo.", veta_cz: "Děkuji za všechno.", en: "thank you", veta_en: "Thank you for everything.", vyslovnost_en: "GRAH-syahs", slovni_druh: "funkční slovo", clen: "" }
];
